# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jacob Rrough
#
# K2 Plus quality presets — machine-specific overrides for CuraEngine.
# These layer on top of the generic SlicePreset with K2-specific tuning:
# input shaping, pressure advance, acceleration limits, chamber heating.

from dataclasses import dataclass
from typing import Dict

from integration.slicer.cura_engine import SlicePreset, PRESETS


@dataclass
class K2MachineOverrides:
    """K2 Plus machine-level settings applied after preset settings."""
    max_acceleration_mm_s2: int = 30000
    max_jerk_mm_s: int = 20
    input_shaping_enabled: bool = True
    pressure_advance_mm: float = 0.04
    chamber_temp_c: int = 0
    filament_diameter_mm: float = 1.75
    nozzle_diameter_mm: float = 0.4


K2_STANDARD = K2MachineOverrides()

K2_HIGH_SPEED = K2MachineOverrides(
    max_acceleration_mm_s2=30000,
    input_shaping_enabled=True,
    pressure_advance_mm=0.035,
)

K2_QUALITY = K2MachineOverrides(
    max_acceleration_mm_s2=10000,
    max_jerk_mm_s=10,
    input_shaping_enabled=True,
    pressure_advance_mm=0.045,
)

K2_ABS = K2MachineOverrides(
    max_acceleration_mm_s2=20000,
    chamber_temp_c=50,
    pressure_advance_mm=0.04,
)


def get_k2_settings(preset_name: str = "standard") -> Dict[str, str]:
    """Get merged CuraEngine settings for K2 Plus with the given preset."""
    preset = PRESETS.get(preset_name, PRESETS["standard"])
    settings = preset.to_cura_settings()

    if preset_name == "high_speed":
        overrides = K2_HIGH_SPEED
    elif preset_name == "quality":
        overrides = K2_QUALITY
    else:
        overrides = K2_STANDARD

    settings.update({
        "machine_width": "350",
        "machine_depth": "350",
        "machine_height": "350",
        "machine_heated_bed": "true",
        "machine_heated_build_volume": "true",
        "machine_nozzle_size": str(overrides.nozzle_diameter_mm),
        "material_diameter": str(overrides.filament_diameter_mm),
        "machine_acceleration": str(overrides.max_acceleration_mm_s2),
        "jerk_print": str(overrides.max_jerk_mm_s),
    })

    return settings


def get_k2_start_gcode(preset_name: str = "standard") -> str:
    """Generate K2 Plus start G-code block with proper homing and heating."""
    preset = PRESETS.get(preset_name, PRESETS["standard"])

    overrides = K2_STANDARD
    if preset_name == "high_speed":
        overrides = K2_HIGH_SPEED
    elif preset_name == "quality":
        overrides = K2_QUALITY

    lines = [
        "; Generated by WorkTrackCAM for Creality K2 Plus",
        f"M104 S{preset.nozzle_temp_c}",
        f"M140 S{preset.bed_temp_c}",
    ]
    if overrides.chamber_temp_c > 0:
        lines.append(f"M141 S{overrides.chamber_temp_c}")
    lines += [
        f"M109 S{preset.nozzle_temp_c}",
        f"M190 S{preset.bed_temp_c}",
        "G28",
        "G1 Z5 F3000",
        "G1 X0.1 Y20 F5000",
        "G1 X0.1 Y200 E15 F1500",
    ]
    return "\n".join(lines)


def get_k2_end_gcode() -> str:
    """Generate K2 Plus end G-code block."""
    return "\n".join([
        "M104 S0",
        "M140 S0",
        "G91",
        "G1 Z10 F3000",
        "G90",
        "G1 X0 Y340 F5000",
        "M84",
    ])
