# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jacob Rrough
#
# FDM passthrough post-processor for Creality K2 Plus (Klipper/Moonraker).
# Emits CuraEngine slicer output verbatim with a WorkTrackCAM header.
#
# Phase 2/3 implementation stub.

try:
    from Path.Post.Processor import PostProcessor

    class KlipperMoonraker(PostProcessor):
        """Klipper/Moonraker FDM passthrough post-processor."""

        def __init__(self, job, **kwargs):
            super().__init__(
                job=job,
                tooltip="Klipper + Moonraker (Creality K2 Plus FDM)",
                tooltipargs=[""],
                units="Metric",
                **kwargs,
            )

        def init_values(self, values):
            super().init_values(values)
            values["MACHINE_NAME"] = "Creality K2 Plus"
            values["ENABLE_COOLANT"] = False
            values["OUTPUT_TOOL_CHANGE"] = False
            values["USE_TLO"] = False
            values["POSTPROCESSOR_FILE_NAME"] = __name__
            values["PREAMBLE"] = "; Generated by WorkTrackCAM for Creality K2 Plus"
            values["POSTAMBLE"] = "; End of WorkTrackCAM output"

except ImportError:
    pass
