# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jacob Rrough
#
# FDM passthrough post-processor for Creality K2 Plus (Klipper/Moonraker).
# Emits CuraEngine slicer output with a WorkTrackCAM header/footer.
#
# Key behaviors:
# - Pre-heat nozzle + bed with M104/M140, wait with M109/M190
# - G28 auto-home before print
# - Prime line at X=0.1
# - End: cool down, retract Z, park Y, disable steppers

PREAMBLE = """\
; Generated by WorkTrackCAM for Creality K2 Plus
; ---------------------------------------------------------------------------
; Build volume: 350 x 350 x 350 mm
; Motion: CoreXY, 600 mm/s max, 30000 mm/s² accel
; Firmware: Creality Klipper OS + Moonraker
; ---------------------------------------------------------------------------"""

POSTAMBLE = """\
M104 S0              ; nozzle heater off
M140 S0              ; bed heater off
G91                  ; relative positioning
G1 Z10 F3000         ; lift nozzle 10mm
G90                  ; absolute positioning
G1 X0 Y340 F5000     ; present print
M84                  ; disable steppers"""

START_GCODE = """\
M104 S{nozzle_temp}
M140 S{bed_temp}
M109 S{nozzle_temp}
M190 S{bed_temp}
G28
G1 Z5 F3000
G1 X0.1 Y20 F5000
G1 X0.1 Y200 E15 F1500"""


try:
    from Path.Post.Processor import PostProcessor

    class KlipperMoonraker(PostProcessor):
        """Klipper/Moonraker FDM passthrough post-processor."""

        def __init__(self, job, **kwargs):
            super().__init__(
                job=job,
                tooltip="Klipper + Moonraker (Creality K2 Plus FDM)",
                tooltipargs=[""],
                units="Metric",
                **kwargs,
            )

        def init_values(self, values):
            super().init_values(values)
            values["MACHINE_NAME"] = "Creality K2 Plus"
            values["ENABLE_COOLANT"] = False
            values["OUTPUT_TOOL_CHANGE"] = False
            values["USE_TLO"] = False
            values["POSTPROCESSOR_FILE_NAME"] = __name__
            values["PREAMBLE"] = (
                "; Generated by WorkTrackCAM for Creality K2 Plus\n"
                "M104 S210\n"
                "M140 S60\n"
                "M109 S210\n"
                "M190 S60\n"
                "G28\n"
                "G1 Z5 F3000\n"
                "G1 X0.1 Y20 F5000\n"
                "G1 X0.1 Y200 E15 F1500"
            )
            values["POSTAMBLE"] = (
                "M104 S0\n"
                "M140 S0\n"
                "G91\n"
                "G1 Z10 F3000\n"
                "G90\n"
                "G1 X0 Y340 F5000\n"
                "M84"
            )

        @property
        def tooltip(self):
            return (
                "Post-processor for Creality K2 Plus FDM printer.\n"
                "Klipper firmware with Moonraker API for direct upload.\n"
                "Includes auto-home, prime line, and proper cooldown sequence."
            )

except ImportError:
    pass
