/**
 * Carvera-specific zeroing / setup G-code generators.
 *
 * The Makera Carvera runs Smoothieware firmware (GRBL-compatible).
 * Key machine facts:
 *  - M2 ends a program (NEVER M30 — M30 deletes the file from the SD card)
 *  - A-axis is the 4th-axis rotary (rotation around X, Carvera 4th Axis HD)
 *  - Z=0 for 4-axis work is at the stock CENTER (rotation axis), NOT the surface
 *  - Spindle range: 6000–15 000 RPM
 *  - G28.3 A0 — set current A position as zero
 *  - G10 L20 P<n> <axes> — set current WCS position as zero
 *  - G38.2 Z-<dist> F<feed> — probe downward until contact (wireless probe T0)
 */

// ── Types ───────────────────────────────────────────────────────────────────────

/** Discriminant for the kind of zeroing / setup program to generate. */
export type CarveraZeroingMode =
  | 'a_axis_zero'
  | 'wcs_zero'
  | 'z_probe'
  | 'full_4axis_setup'
  | 'preflight_check'

/** A single item in the operator preflight checklist. */
export type CarveraPreflightItem = {
  id: string
  label: string
  checked: boolean
  critical: boolean
  description: string
}

// ── Constants ───────────────────────────────────────────────────────────────────

const CARVERA_MIN_SPINDLE_RPM = 6000
const CARVERA_MAX_SPINDLE_RPM = 15000

const DEFAULT_PROBE_DIST_MM = 50
const DEFAULT_PROBE_FEED_MM_MIN = 100
const DEFAULT_RETRACT_MM = 5

// ── Helpers ─────────────────────────────────────────────────────────────────────

/** Build the standard preamble shared by every zeroing program. */
function preamble(title: string): string {
  return [
    `; ── ${title} ──`,
    '; Machine: Makera Carvera (Smoothieware)',
    '; Generated by WorkTrackCAM',
    ';',
    'G21 ; millimeters',
    'G90 ; absolute positioning',
  ].join('\n')
}

/** Canonical program end — always M2, never M30. */
function programEnd(): string {
  return [
    ';',
    '; End program (M2 — safe for Smoothieware SD card)',
    'M2',
  ].join('\n')
}

// ── Public generators ───────────────────────────────────────────────────────────

/**
 * Generate G-code to zero the A-axis at the current physical position.
 *
 * Uses G28.3 A0 which tells Smoothieware "the current A position IS zero"
 * without any motion.
 */
export function generateCarveraAAxisZero(): string {
  return [
    preamble('A-Axis Zero — set current A position as 0'),
    ';',
    '; G28.3 A0: declare current A position = 0 (no motion)',
    'G28.3 A0',
    programEnd(),
  ].join('\n')
}

/**
 * Generate G-code to set WCS zero at the current position for the requested
 * axes. Uses G10 L20 to update the active WCS without motion.
 *
 * @param opts.axes   Which axes to zero (any combination of x, y, z, a).
 * @param opts.wcsIndex  WCS number — 1 = G54, 2 = G55, etc.  Defaults to 1.
 */
export function generateCarveraWcsZero(opts: {
  axes: ('x' | 'y' | 'z' | 'a')[]
  wcsIndex?: number
}): string {
  const wcs = opts.wcsIndex ?? 1
  const axisArgs = opts.axes.map((a) => `${a.toUpperCase()}0`).join(' ')

  return [
    preamble(`WCS Zero — set ${opts.axes.join(', ').toUpperCase()} = 0 in WCS P${wcs} (G5${3 + wcs})`),
    ';',
    `; G10 L20 P${wcs}: set current position as zero for selected axes`,
    `G10 L20 P${wcs} ${axisArgs}`,
    programEnd(),
  ].join('\n')
}

/**
 * Generate G-code for Z probing with the Carvera wireless probe (T0).
 *
 * Sequence:
 *  1. Load wireless probe (M6 T0)
 *  2. Probe downward until contact (G38.2)
 *  3. Set Z=0 at contact point (G10 L20)
 *  4. Retract to a safe clearance height
 *
 * @param opts.probeDistMm      Maximum distance to probe downward (default 50 mm).
 * @param opts.probeFeedMmMin   Feed rate during probing (default 100 mm/min).
 * @param opts.retractMm        Distance to retract after contact (default 5 mm).
 */
export function generateCarveraZProbe(opts?: {
  probeDistMm?: number
  probeFeedMmMin?: number
  retractMm?: number
}): string {
  const dist = opts?.probeDistMm ?? DEFAULT_PROBE_DIST_MM
  const feed = opts?.probeFeedMmMin ?? DEFAULT_PROBE_FEED_MM_MIN
  const retract = opts?.retractMm ?? DEFAULT_RETRACT_MM

  return [
    preamble('Z Probe — find Z zero with wireless probe'),
    ';',
    '; Load wireless probe tool (T0)',
    'M6 T0',
    ';',
    `; Probe downward up to ${dist} mm at ${feed} mm/min until contact`,
    `G38.2 Z-${dist} F${feed}`,
    ';',
    '; Set Z=0 at the probe contact point (WCS P1 / G54)',
    'G10 L20 P1 Z0',
    ';',
    `; Retract ${retract} mm above the new Z zero`,
    `G0 Z${retract}`,
    programEnd(),
  ].join('\n')
}

/**
 * Generate a full 4-axis setup program.
 *
 * Sequence:
 *  1. Zero the A-axis at current position (G28.3 A0)
 *  2. Probe Z to find stock surface / rotation-axis centre
 *
 * IMPORTANT: For 4-axis work, Z=0 is at the rotation-axis centre
 * (stock centre), NOT the surface. The operator must position the
 * probe tip at the stock centre height before running this program,
 * or account for the stock radius offset after probing.
 */
export function generateCarvera4AxisSetup(opts?: {
  probeFeedMmMin?: number
  probeDistMm?: number
}): string {
  const dist = opts?.probeDistMm ?? DEFAULT_PROBE_DIST_MM
  const feed = opts?.probeFeedMmMin ?? DEFAULT_PROBE_FEED_MM_MIN

  return [
    preamble('Full 4-Axis Setup — A-axis zero + Z probe'),
    ';',
    '; IMPORTANT: For 4-axis work Z=0 is at the ROTATION AXIS',
    '; (stock centre), NOT the stock surface. Ensure the probe',
    '; is positioned at the correct reference height.',
    ';',
    '; ── Step 1: Zero A-axis at current position ──',
    'G28.3 A0',
    ';',
    '; ── Step 2: Probe Z to find zero ──',
    '; Load wireless probe tool (T0)',
    'M6 T0',
    ';',
    `; Probe downward up to ${dist} mm at ${feed} mm/min until contact`,
    `G38.2 Z-${dist} F${feed}`,
    ';',
    '; Set Z=0 at probe contact point',
    'G10 L20 P1 Z0',
    ';',
    '; Retract to safe height above new Z zero',
    'G0 Z5',
    ';',
    '; Set A=0 in WCS as well',
    'G10 L20 P1 A0',
    programEnd(),
  ].join('\n')
}

/**
 * Generate a dry-run preflight G-code that lets the operator verify the
 * machine will stay within bounds before cutting.
 *
 * The spindle speed is set (S word) but the spindle is NOT started (no M3).
 * The machine moves to each XY corner of the work area at 10 % of the
 * specified feed rate, then returns to the origin.
 *
 * @param opts.spindleRpm  Intended spindle speed — set but not started.
 * @param opts.feedMmMin   Intended cutting feed — moves run at 10 %.
 */
export function generateCarveraPreflightCheck(opts: {
  spindleRpm?: number
  feedMmMin?: number
}): string {
  const rpm = opts.spindleRpm ?? CARVERA_MIN_SPINDLE_RPM
  const feed = opts.feedMmMin ?? 1000
  const dryFeed = Math.round(feed * 0.1)

  return [
    preamble('Preflight Check — dry run to verify XY bounds'),
    ';',
    '; Spindle speed is set but NOT started (no M3).',
    '; The machine traces the XY bounding corners at 10% feed',
    '; so the operator can verify clearance.',
    ';',
    `; Intended RPM: ${rpm}   Intended feed: ${feed} mm/min`,
    `; Dry-run feed: ${dryFeed} mm/min (10%)`,
    ';',
    `S${rpm} ; set spindle speed (spindle stays OFF)`,
    ';',
    '; Move to safe Z height',
    'G0 Z10',
    ';',
    '; Trace XY bounding corners',
    `G1 X0 Y0 F${dryFeed} ; origin`,
    `G1 X100 Y0 F${dryFeed} ; +X edge`,
    `G1 X100 Y100 F${dryFeed} ; +X +Y corner`,
    `G1 X0 Y100 F${dryFeed} ; +Y edge`,
    `G1 X0 Y0 F${dryFeed} ; back to origin`,
    ';',
    '; Return to origin',
    'G0 X0 Y0',
    'G0 Z10',
    programEnd(),
  ].join('\n')
}

// ── Validation ──────────────────────────────────────────────────────────────────

/**
 * Validate and clamp a spindle RPM value to the machine's supported range.
 *
 * @returns An object with the validity flag, clamped value, and an optional
 *          warning string if clamping was applied.
 */
export function validateSpindleRpm(
  rpm: number,
  machine: { minSpindleRpm?: number; maxSpindleRpm?: number }
): { valid: boolean; clampedRpm: number; warning?: string } {
  const min = machine.minSpindleRpm ?? CARVERA_MIN_SPINDLE_RPM
  const max = machine.maxSpindleRpm ?? CARVERA_MAX_SPINDLE_RPM

  if (!Number.isFinite(rpm) || rpm <= 0) {
    return {
      valid: false,
      clampedRpm: min,
      warning: `Invalid RPM (${rpm}). Clamped to minimum ${min} RPM.`,
    }
  }

  if (rpm < min) {
    return {
      valid: false,
      clampedRpm: min,
      warning: `RPM ${rpm} is below minimum ${min}. Clamped to ${min} RPM.`,
    }
  }

  if (rpm > max) {
    return {
      valid: false,
      clampedRpm: max,
      warning: `RPM ${rpm} exceeds maximum ${max}. Clamped to ${max} RPM.`,
    }
  }

  return { valid: true, clampedRpm: rpm }
}

// ── Preflight checklist ─────────────────────────────────────────────────────────

/**
 * Return the operator preflight checklist for a Carvera job.
 *
 * All items start unchecked (`checked: false`).  Items marked `critical: true`
 * should block the job from starting until acknowledged.
 */
export function getCarveraPreflightChecklist(opts: {
  is4Axis: boolean
}): CarveraPreflightItem[] {
  const common: CarveraPreflightItem[] = [
    {
      id: 'enclosure_closed',
      label: 'Enclosure closed',
      checked: false,
      critical: true,
      description: 'Verify the Carvera enclosure is fully closed and latched.',
    },
    {
      id: 'correct_tool',
      label: 'Correct tool loaded',
      checked: false,
      critical: true,
      description: 'Confirm the correct cutting tool is loaded in the spindle.',
    },
    {
      id: 'dust_collection',
      label: 'Dust collection active',
      checked: false,
      critical: false,
      description: 'Ensure vacuum or dust shoe is connected and running.',
    },
  ]

  if (opts.is4Axis) {
    return [
      ...common,
      {
        id: 'rotary_secured',
        label: 'Rotary attachment secured',
        checked: false,
        critical: true,
        description:
          'Verify the 4th-axis rotary attachment is securely bolted to the bed.',
      },
      {
        id: 'stock_centered',
        label: 'Stock centered on rotary',
        checked: false,
        critical: true,
        description:
          'Confirm the stock is centered between the chuck and tailstock with minimal runout.',
      },
      {
        id: 'tailstock_engaged',
        label: 'Tailstock engaged',
        checked: false,
        critical: true,
        description:
          'Ensure the tailstock is engaged and applying firm pressure to the stock.',
      },
      {
        id: 'z_zero_at_center',
        label: 'Z=0 at rotation axis center',
        checked: false,
        critical: true,
        description:
          'For 4-axis work, Z=0 must be at the rotation axis (stock center), NOT the surface.',
      },
      {
        id: 'a_zero_set',
        label: 'A=0 set',
        checked: false,
        critical: true,
        description:
          'A-axis zero has been set at the desired starting orientation.',
      },
    ]
  }

  // 3-axis checklist
  return [
    ...common,
    {
      id: 'workpiece_clamped',
      label: 'Workpiece clamped',
      checked: false,
      critical: true,
      description:
        'Verify the workpiece is securely clamped to the bed with adequate hold-down force.',
    },
    {
      id: 'wcs_zeroed',
      label: 'WCS zeroed',
      checked: false,
      critical: true,
      description:
        'Work coordinate system (X, Y, Z zero) has been set correctly.',
    },
  ]
}
