/**
 * First-launch project wizard — wire contract shared between the
 * renderer (`FirstLaunchWizard.tsx`) and the main process
 * (`ipc-core.ts` handlers `samples:list` and `wizard:copySample`).
 *
 * The wizard replaces the legacy informational `OnboardingOverlay` with a
 * 3-step flow that creates a real project on Finish:
 *   1. Welcome     — name + parent folder + recent-projects MRU
 *   2. Pick machine — exactly the three target machines (CLAUDE.md
 *                     My-Shop-Only mode); the Carvera card carries a
 *                     3-axis / 4-axis sub-toggle since the registry has
 *                     two profile IDs for it (matches `EnvironmentSplash`)
 *   3. Starter content — empty / sample STL / import existing
 *
 * The contract here is intentionally tiny and additive — the wizard
 * still funnels through the existing `project:create` IPC (no new
 * project schema). Only the *sample bundle* and *availability check*
 * needs a new IPC because the renderer can't touch `resources/samples/`
 * directly from the sandbox.
 */

/** Machine IDs that the wizard offers as starter cards. */
export type WizardStarterMachineId =
  | 'creality-k2-plus'
  | 'laguna-swift-5x10'
  | 'makera-carvera-3axis'
  | 'makera-carvera-4axis'

/**
 * Bundled-sample filename convention under `resources/samples/<machineId>/`.
 *
 * Most samples are binary STL meshes (the wizard's Step 3 radio is still
 * labelled "Sample STL for this machine"), but the Laguna Swift 5x10
 * starter is a 2D contour cut and ships as a DXF instead -- much better
 * representation for a sign-board outline than a flat extruded STL would
 * be. The wizard treats either extension as a valid starter asset; the
 * `samples:list` IPC just checks file existence by name.
 *
 * Files live in `resources/samples/<machineId>/<filename>` and are
 * generated by `scripts/sample-stl-gen/`. See `resources/samples/README.md`
 * for the convention and the per-file geometry origin.
 */
export const WIZARD_MACHINE_TO_SAMPLE_FILE: Readonly<
  Record<WizardStarterMachineId, string>
> = {
  'creality-k2-plus': 'calibration-cube-20mm.stl',
  'laguna-swift-5x10': 'sign-board-sample.dxf',
  'makera-carvera-3axis': 'carvera-pocket-sample.stl',
  'makera-carvera-4axis': 'carvera-rotary-pen-sample.stl'
}

/** Result of `samples:list` — which machines currently have a bundled sample. */
export interface WizardSamplesAvailability {
  readonly availableMachineIds: readonly WizardStarterMachineId[]
}

/** Payload for `wizard:copySample` — copy bundled sample to project assets. */
export interface WizardCopySampleRequest {
  /** Absolute path to the freshly-created project directory. */
  readonly projectDir: string
  /** Machine ID whose sample bundle should be copied. */
  readonly machineId: WizardStarterMachineId
}

/** Result of `wizard:copySample`. */
export type WizardCopySampleResult =
  | { ok: true; /** Path relative to project dir, POSIX-style. */ assetRelativePath: string }
  | { ok: false; error: string }

/**
 * Bundled CadQuery sample script per-machine, used by the wizard's
 * "Start a parametric design" 4th starter option (UNIFY 2). The wizard
 * reads these from `resources/samples/cad/<filename>` via the
 * `wizard:readCadSample` IPC and seeds them as the project's first
 * `designModel`.
 *
 * Convention:
 *   - K2 Plus (FDM) reuses the bracket -- the same parametric L-bracket
 *     prints well on the K2 and exercises a basic extrude + holes script
 *     before the user dives into CAD-specific FDM geometry.
 *   - Laguna Swift 5x10 (full-sheet router) gets the sign-board, the
 *     canonical v-carve / pocket starter.
 *   - Carvera 3-axis gets the L-bracket as a small precision-milling
 *     starter (matches the bracket's hole + fillet feature set).
 *   - Carvera 4-axis HD gets the cylinder + helical groove, the obvious
 *     rotary-axis sample.
 */
export const WIZARD_MACHINE_TO_CAD_SAMPLE: Readonly<
  Record<WizardStarterMachineId, { fileName: string; designName: string }>
> = {
  'creality-k2-plus': { fileName: 'bracket.cq.py', designName: 'L-Bracket' },
  'laguna-swift-5x10': { fileName: 'sign.cq.py', designName: 'Sign Board' },
  'makera-carvera-3axis': { fileName: 'bracket.cq.py', designName: 'L-Bracket' },
  'makera-carvera-4axis': { fileName: 'cylinder.cq.py', designName: 'Rotary Cylinder' }
}

/** Payload for `wizard:readCadSample` -- read a bundled CadQuery sample by machine. */
export interface WizardReadCadSampleRequest {
  /** Machine ID whose CAD starter script should be loaded. */
  readonly machineId: WizardStarterMachineId
}

/** Result of `wizard:readCadSample`. */
export type WizardReadCadSampleResult =
  | {
      ok: true
      /** Display name suggested for the seeded design model. */
      designName: string
      /** Bundled script filename (e.g. `bracket.cq.py`). */
      fileName: string
      /** Raw CadQuery script text -- becomes `designModels[0].scriptText`. */
      scriptText: string
    }
  | { ok: false; error: string }

/** Returns true when the given machine id is one of the four wizard cards. */
export function isWizardStarterMachineId(
  value: unknown
): value is WizardStarterMachineId {
  return (
    value === 'creality-k2-plus' ||
    value === 'laguna-swift-5x10' ||
    value === 'makera-carvera-3axis' ||
    value === 'makera-carvera-4axis'
  )
}
