/**
 * Tests for `gcode-header-health.ts` -- the pure parser used by
 * `moonraker-push.ts` to surface advisory K2 Plus header diagnostics
 * (estimated time, filament use, layer count, embedded thumbnail PNG).
 *
 * Quick-win bundle (undo/redo + K2 thumbnail + Klipper header).
 */
import { describe, expect, it } from 'vitest'
import { checkGcodeHeaderHealth, hasThumbnailBlock } from './gcode-header-health'

// ── Fixtures ─────────────────────────────────────────────────────────────────

const ORCA_HEADER_FULL = [
  '; generated by OrcaSlicer 2.1.1 on 2026-05-27 at 09:00:00 UTC',
  '; estimated printing time (normal mode) = 1h 23m 45s',
  '; filament used [mm] = 1234.56',
  '; filament used [g] = 12.34',
  '; total layer number: 88',
  '; thumbnail begin 300x300 8400',
  '; iVBORw0KGgoAAAANSUhEUgAAASwAAA...',
  '; ...moreBase64...',
  '; thumbnail end',
  '; thumbnail begin 96x96 1024',
  '; iVBOR...',
  '; thumbnail end',
  'M140 S60',
  'M104 S210',
  'G28',
  '',
].join('\n')

const ORCA_HEADER_NO_THUMBNAIL = [
  '; generated by OrcaSlicer 2.1.1 on 2026-05-27',
  '; estimated printing time (normal mode) = 1h 23m 45s',
  '; filament used [mm] = 1234.56',
  '; total layer number: 88',
  'M140 S60',
  'M104 S210',
  'G28',
  '',
].join('\n')

const CURA_HEADER = [
  ';FLAVOR:Marlin',
  ';TIME:5025',
  ';Filament used: 1.2345m',
  ';Layer height: 0.2',
  ';LAYER_COUNT:88',
  'M140 S60',
  'M104 S210',
  '',
].join('\n')

const CNC_LAGUNA_HEADER = [
  '; VCarve Pro 11.5 / mach3',
  'G21',
  'G90',
  'G17',
  'G54',
  'T1 M6',
  'M3 S18000',
  'G0 Z25',
  '',
].join('\n')

// ── hasThumbnailBlock ────────────────────────────────────────────────────────

describe('hasThumbnailBlock', () => {
  it('returns true for an OrcaSlicer-style block', () => {
    expect(hasThumbnailBlock(ORCA_HEADER_FULL)).toBe(true)
  })

  it('returns false when the block is absent', () => {
    expect(hasThumbnailBlock(ORCA_HEADER_NO_THUMBNAIL)).toBe(false)
  })

  it('returns false for a CNC Laguna header', () => {
    expect(hasThumbnailBlock(CNC_LAGUNA_HEADER)).toBe(false)
  })

  it('is case-insensitive (matches `; THUMBNAIL BEGIN ...`)', () => {
    expect(hasThumbnailBlock('; THUMBNAIL BEGIN 300x300 1000\n')).toBe(true)
  })

  it('does NOT match a `; thumbnail end` line alone', () => {
    expect(hasThumbnailBlock('; thumbnail end\n')).toBe(false)
  })

  it('matches with extra whitespace tolerance', () => {
    expect(hasThumbnailBlock('; thumbnail   begin   64x64   512\n')).toBe(true)
  })

  it('returns false on empty input', () => {
    expect(hasThumbnailBlock('')).toBe(false)
  })

  it('returns false on header that only mentions "thumbnail" in a comment', () => {
    expect(hasThumbnailBlock('; this file has no thumbnail; sorry\n')).toBe(false)
  })
})

// ── checkGcodeHeaderHealth: full happy path ─────────────────────────────────

describe('checkGcodeHeaderHealth (OrcaSlicer full header)', () => {
  it('returns ok=true with every field populated', () => {
    const r = checkGcodeHeaderHealth(ORCA_HEADER_FULL)
    expect(r.ok).toBe(true)
    expect(r.missingFields).toEqual([])
    expect(r.fields.timeSeconds).toBe(1 * 3600 + 23 * 60 + 45)
    expect(r.fields.filament?.mm).toBeCloseTo(1234.56)
    expect(r.fields.filament?.grams).toBeCloseTo(12.34)
    expect(r.fields.layerCount).toBe(88)
    expect(r.fields.thumbnail?.widthPx).toBe(300)
    expect(r.fields.thumbnail?.heightPx).toBe(300)
    expect(r.fields.thumbnail?.bytes).toBe(8400)
  })

  it('empty summary when ok=true', () => {
    const r = checkGcodeHeaderHealth(ORCA_HEADER_FULL)
    expect(r.summary).toBe('')
  })
})

// ── checkGcodeHeaderHealth: Cura header ─────────────────────────────────────

describe('checkGcodeHeaderHealth (Cura/Creality Print header)', () => {
  it('parses Cura time + filament + layer count', () => {
    const r = checkGcodeHeaderHealth(CURA_HEADER)
    expect(r.fields.timeSeconds).toBe(5025)
    expect(r.fields.filament?.mm).toBeCloseTo(1234.5, 1) // 1.2345m -> 1234.5mm
    expect(r.fields.layerCount).toBe(88)
  })

  it('flags missing thumbnail in a Cura-style header', () => {
    const r = checkGcodeHeaderHealth(CURA_HEADER)
    expect(r.ok).toBe(false)
    expect(r.missingFields).toContain('thumbnail')
  })
})

// ── checkGcodeHeaderHealth: missing thumbnail ───────────────────────────────

describe('checkGcodeHeaderHealth (OrcaSlicer without thumbnail)', () => {
  it('returns ok=false and reports thumbnail in missingFields', () => {
    const r = checkGcodeHeaderHealth(ORCA_HEADER_NO_THUMBNAIL)
    expect(r.ok).toBe(false)
    expect(r.missingFields).toEqual(['thumbnail'])
  })

  it('non-empty summary mentions the missing thumbnail', () => {
    const r = checkGcodeHeaderHealth(ORCA_HEADER_NO_THUMBNAIL)
    expect(r.summary).toMatch(/thumbnail/)
    expect(r.summary).toMatch(/Mainsail\/Fluidd|Upload will still work/i)
  })
})

// ── checkGcodeHeaderHealth: CNC file ────────────────────────────────────────

describe('checkGcodeHeaderHealth (Laguna CNC header)', () => {
  it('reports every advisory field missing (no slicer metadata)', () => {
    const r = checkGcodeHeaderHealth(CNC_LAGUNA_HEADER)
    expect(r.ok).toBe(false)
    expect(r.missingFields.sort()).toEqual(
      ['filament', 'layerCount', 'thumbnail', 'time'].sort(),
    )
  })
})

// ── Slic3r legacy ───────────────────────────────────────────────────────────

describe('checkGcodeHeaderHealth (Slic3r legacy comments)', () => {
  it('parses ;PRINT_TIME and ;Filament length', () => {
    const text = ';PRINT_TIME:7200\n;Filament length:5000\n;LAYER_COUNT:50\n'
    const r = checkGcodeHeaderHealth(text)
    expect(r.fields.timeSeconds).toBe(7200)
    expect(r.fields.filament?.mm).toBe(5000)
    expect(r.fields.layerCount).toBe(50)
  })
})

// ── Time parsing edge cases ─────────────────────────────────────────────────

describe('checkGcodeHeaderHealth time parsing', () => {
  it('OrcaSlicer time with only seconds parses', () => {
    const r = checkGcodeHeaderHealth(
      '; estimated printing time (normal mode) = 45s\n',
    )
    expect(r.fields.timeSeconds).toBe(45)
  })

  it('OrcaSlicer time with days+hours+minutes+seconds parses', () => {
    const r = checkGcodeHeaderHealth(
      '; estimated printing time (normal mode) = 1d 2h 3m 4s\n',
    )
    expect(r.fields.timeSeconds).toBe(86400 + 2 * 3600 + 3 * 60 + 4)
  })

  it('Cura TIME with explicit zero is parsed as 0', () => {
    const r = checkGcodeHeaderHealth(';TIME:0\n')
    expect(r.fields.timeSeconds).toBe(0)
  })

  it('returns undefined time on a malformed header', () => {
    const r = checkGcodeHeaderHealth('; nothing useful here\n')
    expect(r.fields.timeSeconds).toBeUndefined()
  })
})

// ── Edge cases ──────────────────────────────────────────────────────────────

describe('checkGcodeHeaderHealth edge cases', () => {
  it('empty string -> every field missing, ok=false', () => {
    const r = checkGcodeHeaderHealth('')
    expect(r.ok).toBe(false)
    expect(r.missingFields).toHaveLength(4)
  })

  it('does not throw on garbage input', () => {
    expect(() => checkGcodeHeaderHealth('\x00\x01\x02')).not.toThrow()
  })

  it('returns ok=true even when the thumbnail byte count is 0 (block is present)', () => {
    // Some Slic3r forks emit a 0-byte placeholder block. The block is still
    // a positive signal that the slicer was instructed to emit one.
    const r = checkGcodeHeaderHealth(
      ';TIME:60\n;Filament used: 1m\n;LAYER_COUNT:10\n; thumbnail begin 16x16 0\n',
    )
    expect(r.ok).toBe(true)
    expect(r.fields.thumbnail?.bytes).toBe(0)
  })

  it('preserves both mm and grams when both filament comments are present', () => {
    const r = checkGcodeHeaderHealth(
      '; filament used [mm] = 100\n; filament used [g] = 0.3\n',
    )
    expect(r.fields.filament?.mm).toBe(100)
    expect(r.fields.filament?.grams).toBe(0.3)
  })

  it('falls back to Cura `;Filament used:` only when Orca-style is absent', () => {
    const text = '; filament used [mm] = 100\n;Filament used: 2m\n'
    const r = checkGcodeHeaderHealth(text)
    // OrcaSlicer comment wins
    expect(r.fields.filament?.mm).toBe(100)
  })
})
