/**
 * Probing cycle G-code generators for CNC machines with touch probes.
 *
 * Each generator emits safe, self-contained G-code blocks that:
 *  1. Retract to a safety height before every probe move
 *  2. Perform G38.2 probe moves at the specified feed rate
 *  3. Store probe results in # variables (#5061 X, #5062 Y, #5063 Z)
 *  4. Set WCS offsets via G10 L2 P<n> (absolute WCS offset assignment)
 *  5. Retract after the probe sequence completes
 *
 * Safety: Every probe move is preceded by a retract. Bad probe G-code can
 * crash a machine or break a probe stylus. Verify on your controller before
 * running on real hardware.
 *
 * Variable mapping (Fanuc/LinuxCNC/Mach3 convention):
 *   #5061 = last probe X position
 *   #5062 = last probe Y position
 *   #5063 = last probe Z position
 */

// ── Types ───────────────────────────────────────────────────────────────────────

export type ProbeCycleType =
  | 'singleSurface'
  | 'boreCenter'
  | 'bossCenter'
  | 'cornerFind'
  | 'toolLength'

/** Common parameters shared by all probe cycle types. */
export type ProbeBaseParams = {
  /** Probe feed rate in mm/min (typical: 50-200). */
  probeFeedMmMin: number
  /** Retract distance in mm after each probe touch (typical: 2-5). */
  retractMm: number
  /** WCS index: 1=G54, 2=G55, ... 6=G59. */
  wcsIndex: number
}

export type SingleSurfaceParams = ProbeBaseParams & {
  /** Axis to probe along: 'x', 'y', or 'z'. */
  axis: 'x' | 'y' | 'z'
  /** Direction of probe travel: +1 or -1. */
  direction: 1 | -1
  /** Maximum distance to probe before giving up (mm). */
  maxTravelMm: number
  /** Expected surface position for the comment (informational). */
  expectedPositionMm?: number
}

export type BoreCenterParams = ProbeBaseParams & {
  /** Approximate bore diameter in mm (determines probe travel). */
  approxDiameterMm: number
  /** Z depth to descend into bore before probing XY walls. */
  probeDepthMm: number
}

export type BossCenterParams = ProbeBaseParams & {
  /** Approximate boss diameter/width in mm (determines probe travel). */
  approxWidthMm: number
  /** Z height to probe boss faces at. */
  probeHeightMm: number
}

export type CornerFindParams = ProbeBaseParams & {
  /** Maximum X travel from starting position toward the corner face. */
  maxTravelXMm: number
  /** Maximum Y travel from starting position toward the corner face. */
  maxTravelYMm: number
}

export type ToolLengthParams = ProbeBaseParams & {
  /** Maximum Z travel toward the tool setter surface. */
  maxTravelMm: number
  /** Known Z height of the tool setter surface (for reference in comments). */
  toolSetterHeightMm?: number
}

// ── Helpers ─────────────────────────────────────────────────────────────────────

function commentLine(text: string): string {
  return `; ${text}`
}

function headerBlock(title: string): string {
  return [
    commentLine(`── ${title} ──`),
    commentLine('Generated by WorkTrackCAM'),
    commentLine('VERIFY ON YOUR CONTROLLER BEFORE RUNNING ON REAL HARDWARE'),
    commentLine(''),
  ].join('\n')
}

/**
 * Convert WCS index (1-6) to the P parameter for G10 L2.
 * P1 = G54, P2 = G55, ..., P6 = G59.
 */
function wcsP(wcsIndex: number): number {
  return Math.max(1, Math.min(6, Math.round(wcsIndex)))
}

function safetyRetract(retractMm: number): string {
  return `G91 G0 Z${retractMm}\nG90`
}

// ── Generators ──────────────────────────────────────────────────────────────────

/**
 * Single-surface probe: probe toward a surface along one axis,
 * set the WCS offset for that axis at the contact point.
 */
export function generateSingleSurfaceProbe(params: SingleSurfaceParams): string {
  const { axis, direction, maxTravelMm, probeFeedMmMin, retractMm, wcsIndex, expectedPositionMm } = params
  const axisUpper = axis.toUpperCase()
  const travel = direction * maxTravelMm
  const p = wcsP(wcsIndex)

  // Variable for the probed axis: X=#5061, Y=#5062, Z=#5063
  const varNum = axis === 'x' ? 5061 : axis === 'y' ? 5062 : 5063

  const lines: string[] = [
    headerBlock(`Single Surface Probe — ${axisUpper} axis`),
    commentLine(`Axis: ${axisUpper}, Direction: ${direction > 0 ? '+' : '-'}, Max travel: ${maxTravelMm} mm`),
    ...(expectedPositionMm != null ? [commentLine(`Expected surface at ${axisUpper}=${expectedPositionMm} mm`)] : []),
    commentLine(`WCS: P${p} (G5${3 + p}), Probe feed: ${probeFeedMmMin} mm/min`),
    '',
    commentLine('Safety retract before probe move'),
    safetyRetract(retractMm),
    '',
    commentLine(`Probe toward ${axisUpper} surface`),
    `G38.2 ${axisUpper}${travel} F${probeFeedMmMin}`,
    '',
    commentLine(`Store probe result: #${varNum} = probed ${axisUpper} position`),
    commentLine(`Set WCS P${p} ${axisUpper} offset to probed position`),
    `G10 L2 P${p} ${axisUpper}[#${varNum}]`,
    '',
    commentLine('Safety retract after probe'),
    safetyRetract(retractMm),
  ]

  return lines.join('\n')
}

/**
 * Bore center probe: probe 4 walls of a bore (+X, -X, +Y, -Y),
 * compute the center, and set WCS XY offset.
 */
export function generateBoreCenterProbe(params: BoreCenterParams): string {
  const { approxDiameterMm, probeDepthMm, probeFeedMmMin, retractMm, wcsIndex } = params
  const p = wcsP(wcsIndex)
  const halfDia = approxDiameterMm / 2

  const lines: string[] = [
    headerBlock('Bore Center Probe — 4-wall XY'),
    commentLine(`Approximate bore diameter: ${approxDiameterMm} mm`),
    commentLine(`Probe depth: ${probeDepthMm} mm, Feed: ${probeFeedMmMin} mm/min`),
    commentLine(`WCS: P${p} (G5${3 + p})`),
    '',
    commentLine('Safety retract before descending into bore'),
    safetyRetract(retractMm),
    '',
    commentLine('Descend to probe depth inside bore'),
    `G91 G0 Z-${probeDepthMm}`,
    'G90',
    '',
    commentLine('--- Probe +X wall ---'),
    commentLine('Safety retract (XY) before probe'),
    safetyRetract(retractMm),
    `G38.2 X${halfDia} F${probeFeedMmMin}`,
    commentLine('Store +X contact in #100'),
    '#100 = #5061',
    commentLine('Retract from +X wall'),
    safetyRetract(retractMm),
    '',
    commentLine('Return to approximate center for next probe'),
    `G91 G0 X-${halfDia}`,
    'G90',
    '',
    commentLine('--- Probe -X wall ---'),
    safetyRetract(retractMm),
    `G38.2 X-${halfDia} F${probeFeedMmMin}`,
    commentLine('Store -X contact in #101'),
    '#101 = #5061',
    commentLine('Retract from -X wall'),
    safetyRetract(retractMm),
    '',
    commentLine('Return to approximate center'),
    `G91 G0 X${halfDia}`,
    'G90',
    '',
    commentLine('--- Probe +Y wall ---'),
    safetyRetract(retractMm),
    `G38.2 Y${halfDia} F${probeFeedMmMin}`,
    commentLine('Store +Y contact in #102'),
    '#102 = #5062',
    commentLine('Retract from +Y wall'),
    safetyRetract(retractMm),
    '',
    commentLine('Return to approximate center'),
    `G91 G0 Y-${halfDia}`,
    'G90',
    '',
    commentLine('--- Probe -Y wall ---'),
    safetyRetract(retractMm),
    `G38.2 Y-${halfDia} F${probeFeedMmMin}`,
    commentLine('Store -Y contact in #103'),
    '#103 = #5062',
    commentLine('Retract from -Y wall'),
    safetyRetract(retractMm),
    '',
    commentLine('--- Compute bore center ---'),
    commentLine('Center X = (#100 + #101) / 2'),
    '#104 = [#100 + #101] / 2',
    commentLine('Center Y = (#102 + #103) / 2'),
    '#105 = [#102 + #103] / 2',
    '',
    commentLine(`Set WCS P${p} XY to bore center`),
    `G10 L2 P${p} X[#104] Y[#105]`,
    '',
    commentLine('Retract out of bore'),
    `G91 G0 Z${probeDepthMm + retractMm}`,
    'G90',
  ]

  return lines.join('\n')
}

/**
 * Boss center probe: probe 4 faces of a boss (+X, -X, +Y, -Y),
 * compute the center, and set WCS XY offset.
 */
export function generateBossCenterProbe(params: BossCenterParams): string {
  const { approxWidthMm, probeHeightMm, probeFeedMmMin, retractMm, wcsIndex } = params
  const p = wcsP(wcsIndex)
  const halfWidth = approxWidthMm / 2
  // Travel past the boss edge to ensure contact
  const travelDist = halfWidth + 10

  const lines: string[] = [
    headerBlock('Boss Center Probe — 4-face XY'),
    commentLine(`Approximate boss width: ${approxWidthMm} mm`),
    commentLine(`Probe height: ${probeHeightMm} mm, Feed: ${probeFeedMmMin} mm/min`),
    commentLine(`WCS: P${p} (G5${3 + p})`),
    '',
    commentLine('Safety retract above boss'),
    safetyRetract(retractMm),
    '',
    commentLine('--- Probe +X face (approach from +X side) ---'),
    commentLine('Move to +X side of boss, then probe inward (-X)'),
    safetyRetract(retractMm),
    `G91 G0 Z-${probeHeightMm}`,
    'G90',
    `G38.2 X-${travelDist} F${probeFeedMmMin}`,
    commentLine('Store +X face contact in #100'),
    '#100 = #5061',
    safetyRetract(retractMm),
    '',
    commentLine('--- Probe -X face (approach from -X side) ---'),
    safetyRetract(retractMm),
    `G91 G0 Z-${probeHeightMm}`,
    'G90',
    `G38.2 X${travelDist} F${probeFeedMmMin}`,
    commentLine('Store -X face contact in #101'),
    '#101 = #5061',
    safetyRetract(retractMm),
    '',
    commentLine('--- Probe +Y face (approach from +Y side) ---'),
    safetyRetract(retractMm),
    `G91 G0 Z-${probeHeightMm}`,
    'G90',
    `G38.2 Y-${travelDist} F${probeFeedMmMin}`,
    commentLine('Store +Y face contact in #102'),
    '#102 = #5062',
    safetyRetract(retractMm),
    '',
    commentLine('--- Probe -Y face (approach from -Y side) ---'),
    safetyRetract(retractMm),
    `G91 G0 Z-${probeHeightMm}`,
    'G90',
    `G38.2 Y${travelDist} F${probeFeedMmMin}`,
    commentLine('Store -Y face contact in #103'),
    '#103 = #5062',
    safetyRetract(retractMm),
    '',
    commentLine('--- Compute boss center ---'),
    commentLine('Center X = (#100 + #101) / 2'),
    '#104 = [#100 + #101] / 2',
    commentLine('Center Y = (#102 + #103) / 2'),
    '#105 = [#102 + #103] / 2',
    '',
    commentLine(`Set WCS P${p} XY to boss center`),
    `G10 L2 P${p} X[#104] Y[#105]`,
    '',
    commentLine('Final safety retract'),
    safetyRetract(retractMm),
  ]

  return lines.join('\n')
}

/**
 * Corner find probe: probe an X face and a Y face to locate
 * the corner, then set WCS XY origin at that corner.
 */
export function generateCornerFindProbe(params: CornerFindParams): string {
  const { maxTravelXMm, maxTravelYMm, probeFeedMmMin, retractMm, wcsIndex } = params
  const p = wcsP(wcsIndex)

  const lines: string[] = [
    headerBlock('Corner Find Probe — X face + Y face'),
    commentLine(`Max travel: X=${maxTravelXMm} mm, Y=${maxTravelYMm} mm`),
    commentLine(`Probe feed: ${probeFeedMmMin} mm/min`),
    commentLine(`WCS: P${p} (G5${3 + p})`),
    '',
    commentLine('Safety retract before X probe'),
    safetyRetract(retractMm),
    '',
    commentLine('--- Probe X face ---'),
    `G38.2 X-${maxTravelXMm} F${probeFeedMmMin}`,
    commentLine('Store X contact position: #5061'),
    '',
    commentLine(`Set WCS P${p} X offset at probed X position`),
    `G10 L2 P${p} X[#5061]`,
    '',
    commentLine('Retract from X face'),
    safetyRetract(retractMm),
    '',
    commentLine('Safety retract before Y probe'),
    safetyRetract(retractMm),
    '',
    commentLine('--- Probe Y face ---'),
    `G38.2 Y-${maxTravelYMm} F${probeFeedMmMin}`,
    commentLine('Store Y contact position: #5062'),
    '',
    commentLine(`Set WCS P${p} Y offset at probed Y position`),
    `G10 L2 P${p} Y[#5062]`,
    '',
    commentLine('Retract from Y face'),
    safetyRetract(retractMm),
    '',
    commentLine('Corner XY origin is now set'),
    commentLine('Final safety retract'),
    safetyRetract(retractMm),
  ]

  return lines.join('\n')
}

/**
 * Tool length probe: probe Z downward onto a tool setter,
 * then set G43 tool length offset.
 */
export function generateToolLengthProbe(params: ToolLengthParams): string {
  const { maxTravelMm, probeFeedMmMin, retractMm, wcsIndex, toolSetterHeightMm } = params
  const p = wcsP(wcsIndex)

  const lines: string[] = [
    headerBlock('Tool Length Probe — Z onto tool setter'),
    commentLine(`Max travel: ${maxTravelMm} mm, Feed: ${probeFeedMmMin} mm/min`),
    ...(toolSetterHeightMm != null ? [commentLine(`Tool setter surface at Z=${toolSetterHeightMm} mm`)] : []),
    commentLine(`WCS: P${p} (G5${3 + p})`),
    '',
    commentLine('Safety retract before Z probe'),
    safetyRetract(retractMm),
    '',
    commentLine('Probe Z downward onto tool setter'),
    `G38.2 Z-${maxTravelMm} F${probeFeedMmMin}`,
    '',
    commentLine('Store Z contact position: #5063'),
    commentLine(`Set WCS P${p} Z offset at probed Z position`),
    `G10 L2 P${p} Z[#5063]`,
    '',
    commentLine('Apply tool length compensation (G43)'),
    'G43 H1',
    '',
    commentLine('Safety retract after Z probe'),
    safetyRetract(retractMm),
  ]

  return lines.join('\n')
}

// ── Dispatcher ──────────────────────────────────────────────────────────────────

/**
 * Generate a probe cycle by type. Dispatches to the appropriate generator.
 */
export function generateProbeCycle(
  type: 'singleSurface',
  params: SingleSurfaceParams
): string
export function generateProbeCycle(
  type: 'boreCenter',
  params: BoreCenterParams
): string
export function generateProbeCycle(
  type: 'bossCenter',
  params: BossCenterParams
): string
export function generateProbeCycle(
  type: 'cornerFind',
  params: CornerFindParams
): string
export function generateProbeCycle(
  type: 'toolLength',
  params: ToolLengthParams
): string
export function generateProbeCycle(
  type: ProbeCycleType,
  params: ProbeBaseParams & Record<string, unknown>
): string
export function generateProbeCycle(
  type: ProbeCycleType,
  params: ProbeBaseParams & Record<string, unknown>
): string {
  switch (type) {
    case 'singleSurface':
      return generateSingleSurfaceProbe(params as SingleSurfaceParams)
    case 'boreCenter':
      return generateBoreCenterProbe(params as BoreCenterParams)
    case 'bossCenter':
      return generateBossCenterProbe(params as BossCenterParams)
    case 'cornerFind':
      return generateCornerFindProbe(params as CornerFindParams)
    case 'toolLength':
      return generateToolLengthProbe(params as ToolLengthParams)
  }
}
