/**
 * gcode-send-gate.test.ts -- Wave 3m behavioral contract for the LIVE
 * send/export safety seam (`gcode-send-gate.ts`).
 *
 * Every test runs the REAL surface action the production button invokes,
 * with the IPC boundary mocked (`window.fab.*` equivalents injected as
 * spies) and the machine dims loaded from the REAL bundled profiles in
 * `resources/machines/*.json` -- so a profile-dim regression or a seam
 * regression both surface here:
 *   - Laguna Swift 5x10  : 1524 x 3048 mm (mach3, safeRetractZMm 25)
 *   - Carvera 3-axis     : 360 x 240 mm   (smoothieware, retract = z 140)
 *   - Carvera 4th-axis   : 240 x 92 mm    (grbl_4axis,  retract = z 46)
 *   - K2 Plus (FDM)      : dims NEVER passed -- advisory-only by contract
 *
 * The blocking paths assert BOTH halves of the safety contract: the
 * dispatch IPC is never invoked AND the honest message reaches the
 * operator via onStatus. The K2 section asserts the inverse: the push can
 * NEVER be blocked by this seam (the main-process temperature validator in
 * moonraker-push.ts -- untouched by Wave 3m -- remains the K2's hard gate).
 */
import { describe, expect, it, vi } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import {
  adviseFdmProgramForPush,
  formatBlockedSendStatus,
  formatSendAdvisoriesStatus,
  formatSetupSheetGateNotice,
  gateCncProgramForSend,
  gateSafeRetractZMm,
  runCarveraUploadSurface,
  runGatedCncSendFlow,
  runK2PushSurface,
  runLagunaExportSurface,
  type GateIo,
  type GateMachine,
  type K2PushMachine
} from './gcode-send-gate'

// --- Real bundled profiles (resources/machines/*.json) ----------------------

const MACHINES_DIR = resolve(__dirname, '..', '..', '..', 'resources', 'machines')

type BundledGateProfile = GateMachine & { readonly id: string; readonly kind: string }

function readBundledProfile(file: string): BundledGateProfile {
  return JSON.parse(readFileSync(resolve(MACHINES_DIR, file), 'utf-8')) as BundledGateProfile
}

const LAGUNA = readBundledProfile('laguna-swift-5x10.json')
const CARVERA3 = readBundledProfile('makera-carvera-3axis.json')
const CARVERA4 = readBundledProfile('makera-carvera-4axis.json')
const K2_PLUS = readBundledProfile('creality-k2-plus.json') as BundledGateProfile & K2PushMachine

// --- Program fixtures --------------------------------------------------------

/** Clean Laguna program (mach3): in-bed unless `moves` says otherwise. */
function lagunaProgram(moves: readonly string[]): string {
  return ['%', 'G21', 'G90', 'G17', 'M3 S18000', ...moves, 'G0 Z25', 'M5', 'G0 Z25', 'M30', '%'].join('\n')
}

/** Clean Carvera program (smoothieware); `retractZ` = profile workAreaMm.z. */
function carveraProgram(moves: readonly string[], retractZ: number): string {
  return [
    'G21',
    'G90',
    'G17',
    'G54',
    'M3 S15000',
    ...moves,
    `G0 Z${retractZ}`,
    'M5',
    `G0 Z${retractZ}`,
    'M30'
  ].join('\n')
}

/**
 * Realistic OrcaSlicer-flavored K2 output: G91 retraction burst, no M5, no
 * M2/M30, park move far outside any bed once mis-parsed as absolute. The
 * CNC gate would block this THREE ways -- the FDM surface must not.
 */
const ORCA_K2_GCODE = [
  '; generated by OrcaSlicer',
  'G21',
  'G90',
  'M82',
  'G28',
  'G1 Z0.2 F600',
  'G1 X340 Y340 E5 F1500',
  'G91',
  'G1 Z5 E-2 F1200',
  'G90',
  'G1 X9000 Y9000 F9000',
  'M104 S0',
  'M140 S0',
  'M84'
].join('\n')

const fakeIo = (text: string): GateIo => ({ readTextFile: vi.fn().mockResolvedValue(text) })
const failingIo = (msg: string): GateIo => ({
  readTextFile: vi.fn().mockRejectedValue(new Error(msg))
})

// === (A) profile threading ===================================================

describe('gateSafeRetractZMm -- real-profile safe-retract threading', () => {
  it('Laguna uses the explicit safeRetractZMm 25', () => {
    expect(gateSafeRetractZMm(LAGUNA)).toBe(25)
  })
  it('Carvera 3-axis falls back to the z envelope (140)', () => {
    expect(gateSafeRetractZMm(CARVERA3)).toBe(140)
  })
  it('Carvera 4th-axis falls back to the z envelope (46)', () => {
    expect(gateSafeRetractZMm(CARVERA4)).toBe(46)
  })
  it('K2 Plus falls back to the z envelope (350)', () => {
    expect(gateSafeRetractZMm(K2_PLUS)).toBe(350)
  })
})

// === (B) Laguna hard gate with the REAL 1524 x 3048 dims =====================

describe('gateCncProgramForSend -- Laguna Swift 5x10 (1524 x 3048 mm)', () => {
  it('X1600 on the 1524 mm axis is BLOCKING and names the real travel', () => {
    const r = gateCncProgramForSend({
      gcode: lagunaProgram(['G1 X1600 Y100 Z-3 F2000']),
      machine: LAGUNA
    })
    expect(r.allowed).toBe(false)
    const msg = r.blockingErrors.find((e) => e.includes('machine X work area'))
    expect(msg).toBeDefined()
    expect(msg).toContain('1524 mm')
  })
  it('Y3100 on the 3048 mm axis is BLOCKING and names the real travel', () => {
    const r = gateCncProgramForSend({
      gcode: lagunaProgram(['G1 X100 Y3100 Z-3 F2000']),
      machine: LAGUNA
    })
    expect(r.allowed).toBe(false)
    expect(r.blockingErrors.some((e) => e.includes('machine Y work area') && e.includes('3048 mm'))).toBe(true)
  })
  it('a full-sheet program inside 1524 x 3048 is allowed with zero blockers', () => {
    const r = gateCncProgramForSend({
      gcode: lagunaProgram(['G1 X1500 Y3000 Z-3 F2000', 'G1 X10 Y10 F2000']),
      machine: LAGUNA
    })
    expect(r.allowed).toBe(true)
    expect(r.blockingErrors).toEqual([])
  })
})

// === (C) Carvera hard gate with the REAL 360 x 240 / 240 x 92 dims ===========

describe('gateCncProgramForSend -- Makera Carvera dims', () => {
  it('3-axis: X400 on the 360 mm bed is BLOCKING with the real travel named', () => {
    const r = gateCncProgramForSend({
      gcode: carveraProgram(['G1 X400 Y100 Z-1 F800'], 140),
      machine: CARVERA3
    })
    expect(r.allowed).toBe(false)
    expect(r.blockingErrors.some((e) => e.includes('machine X work area') && e.includes('360 mm'))).toBe(true)
  })
  it('3-axis: Y300 on the 240 mm axis is BLOCKING', () => {
    const r = gateCncProgramForSend({
      gcode: carveraProgram(['G1 X100 Y300 Z-1 F800'], 140),
      machine: CARVERA3
    })
    expect(r.blockingErrors.some((e) => e.includes('machine Y work area') && e.includes('240 mm'))).toBe(true)
  })
  it('3-axis: an in-bed 350 x 230 program is allowed', () => {
    const r = gateCncProgramForSend({
      gcode: carveraProgram(['G1 X350 Y230 Z-1 F800'], 140),
      machine: CARVERA3
    })
    expect(r.blockingErrors).toEqual([])
  })
  it('4th-axis: X250 exceeds the 240 mm rotary envelope and is BLOCKING', () => {
    const r = gateCncProgramForSend({
      gcode: carveraProgram(['G1 X250 Y10 Z-1 F800'], 46),
      machine: CARVERA4
    })
    expect(r.blockingErrors.some((e) => e.includes('machine X work area') && e.includes('240 mm'))).toBe(true)
  })
})

// === (D) FDM advisory contract -- no blocking channel ========================

describe('adviseFdmProgramForPush -- advisory-only by construction', () => {
  it('returns ONLY a warnings key (no blocking channel exists at all)', () => {
    const r = adviseFdmProgramForPush({ gcode: ORCA_K2_GCODE, machine: K2_PLUS })
    expect(Object.keys(r)).toEqual(['warnings'])
  })
  it('never emits envelope text even for a 9-meter park move (dims withheld)', () => {
    const r = adviseFdmProgramForPush({ gcode: ORCA_K2_GCODE, machine: K2_PLUS })
    expect(r.warnings.some((w) => w.includes('work area'))).toBe(false)
  })
  it('does not leak the CNC M5/M30 blockers into the warnings channel', () => {
    const r = adviseFdmProgramForPush({ gcode: ORCA_K2_GCODE, machine: K2_PLUS })
    expect(r.warnings.some((w) => w.includes('M5') || w.includes('M2/M30'))).toBe(false)
  })
})

// === (E) runGatedCncSendFlow -- the shared CNC flow ==========================

describe('runGatedCncSendFlow -- read, gate, dispatch-or-abort', () => {
  it('BLOCKED: dispatch never runs; the lead status names the action + first error', async () => {
    const statuses: string[] = []
    const dispatch = vi.fn().mockResolvedValue(undefined)
    const outcome = await runGatedCncSendFlow({
      gcodePath: 'C:/job/output/cam.nc',
      machine: LAGUNA,
      actionLabel: 'Send to Carvera',
      io: fakeIo(lagunaProgram(['G1 X1600 Y100 Z-3 F2000'])),
      onStatus: (m) => statuses.push(m),
      dispatch
    })
    expect(outcome).toBe('blocked')
    expect(dispatch).not.toHaveBeenCalled()
    expect(statuses[0]).toContain('Send to Carvera blocked')
    expect(statuses[0]).toContain('posted G-code failed the export safety check')
  })
  it('READ FAILURE: fail-closed -- dispatch never runs, honest abort message', async () => {
    const statuses: string[] = []
    const dispatch = vi.fn().mockResolvedValue(undefined)
    const outcome = await runGatedCncSendFlow({
      gcodePath: 'C:/job/output/cam.nc',
      machine: LAGUNA,
      actionLabel: 'Export for Laguna',
      io: failingIo('ENOENT'),
      onStatus: (m) => statuses.push(m),
      dispatch
    })
    expect(outcome).toBe('read_failed')
    expect(dispatch).not.toHaveBeenCalled()
    expect(statuses[0]).toContain('Export for Laguna aborted')
    expect(statuses[0]).toContain('could not read')
  })
  it('ALLOWED: dispatch receives the EXACT program text the gate verified', async () => {
    const program = lagunaProgram(['G1 X100 Y100 Z-3 F2000'])
    const dispatch = vi.fn().mockResolvedValue(undefined)
    const outcome = await runGatedCncSendFlow({
      gcodePath: 'C:/job/output/cam.nc',
      machine: LAGUNA,
      actionLabel: 'Send to Carvera',
      io: fakeIo(program),
      onStatus: () => undefined,
      dispatch
    })
    expect(outcome).toBe('dispatched')
    expect(dispatch).toHaveBeenCalledTimes(1)
    expect(dispatch).toHaveBeenCalledWith(program)
  })
})

// === (F) Carvera upload surface -- 360 x 240 dims, mocked carvera-cli IPC ====

describe('runCarveraUploadSurface -- the "Upload to Carvera" / "Send to Carvera" action', () => {
  it('BLOCKS an over-bed program: zero upload IPC + operator message with the 360 mm travel', async () => {
    const statuses: string[] = []
    const carveraUpload = vi.fn().mockResolvedValue({ ok: true })
    const outcome = await runCarveraUploadSurface({
      gcodePath: 'C:/job/output/cam.nc',
      gateMachine: CARVERA3,
      connection: 'auto',
      device: undefined,
      timeoutMs: 120_000,
      io: fakeIo(carveraProgram(['G1 X400 Y100 Z-1 F800'], 140)),
      carveraUpload,
      onStatus: (m) => statuses.push(m)
    })
    expect(outcome).toBe('blocked')
    expect(carveraUpload).not.toHaveBeenCalled()
    expect(statuses[0]).toContain('Send to Carvera blocked')
    expect(statuses.join('\n')).toContain('360 mm')
  })
  it('DISPATCHES an in-bed program with the exact upload payload', async () => {
    const statuses: string[] = []
    const carveraUpload = vi.fn().mockResolvedValue({ ok: true })
    const outcome = await runCarveraUploadSurface({
      gcodePath: 'C:/job/output/cam.nc',
      gateMachine: CARVERA3,
      connection: 'wifi',
      device: '192.168.1.77',
      timeoutMs: 120_000,
      io: fakeIo(carveraProgram(['G1 X350 Y230 Z-1 F800'], 140)),
      carveraUpload,
      onStatus: (m) => statuses.push(m)
    })
    expect(outcome).toBe('dispatched')
    expect(carveraUpload).toHaveBeenCalledTimes(1)
    expect(carveraUpload).toHaveBeenCalledWith({
      gcodePath: 'C:/job/output/cam.nc',
      connection: 'wifi',
      device: '192.168.1.77',
      timeoutMs: 120_000
    })
    expect(statuses.some((m) => m.includes('Carvera: file uploaded'))).toBe(true)
  })
  it('surfaces an upload failure verbatim (error + detail)', async () => {
    const statuses: string[] = []
    const carveraUpload = vi
      .fn()
      .mockResolvedValue({ ok: false, error: 'carvera-cli not found', detail: 'set the path in Settings' })
    await runCarveraUploadSurface({
      gcodePath: 'C:/job/output/cam.nc',
      gateMachine: CARVERA3,
      connection: 'auto',
      device: undefined,
      timeoutMs: 120_000,
      io: fakeIo(carveraProgram(['G1 X10 Y10 Z-1 F800'], 140)),
      carveraUpload,
      onStatus: (m) => statuses.push(m)
    })
    expect(statuses.some((m) => m.includes('Carvera upload failed: carvera-cli not found'))).toBe(true)
  })
  it('degrades to the legacy ungated dispatch when no Carvera profile exists', async () => {
    const carveraUpload = vi.fn().mockResolvedValue({ ok: true })
    const outcome = await runCarveraUploadSurface({
      gcodePath: 'C:/job/output/cam.nc',
      gateMachine: undefined,
      connection: 'auto',
      device: undefined,
      timeoutMs: 120_000,
      io: fakeIo('this is never read on the ungated path'),
      carveraUpload,
      onStatus: () => undefined
    })
    expect(outcome).toBe('dispatched_ungated')
    expect(carveraUpload).toHaveBeenCalledTimes(1)
  })
})

// === (G) Laguna export surface -- 1524 x 3048 dims, mocked dialog + fs IPC ===

describe('runLagunaExportSurface -- the "Export for Laguna" action', () => {
  const overBed = lagunaProgram(['G1 X1600 Y3100 Z-3 F2000'])
  const inBed = lagunaProgram(['G1 X1500 Y3000 Z-3 F2000'])

  it('BLOCKS a program exceeding 1524 x 3048: no save dialog, no file write, honest message', async () => {
    const statuses: string[] = []
    const pickSavePath = vi.fn().mockResolvedValue('C:/usb/job.nc')
    const writeTextFile = vi.fn().mockResolvedValue(undefined)
    const outcome = await runLagunaExportSurface({
      gcodePath: 'C:/job/output/cam.nc',
      gateMachine: LAGUNA,
      suggestedPath: 'C:/job/output/job_laguna.nc',
      io: fakeIo(overBed),
      pickSavePath,
      writeTextFile,
      onStatus: (m) => statuses.push(m)
    })
    expect(outcome).toBe('blocked')
    expect(pickSavePath).not.toHaveBeenCalled()
    expect(writeTextFile).not.toHaveBeenCalled()
    expect(statuses[0]).toContain('Export for Laguna blocked')
    expect(statuses.join('\n')).toContain('1524 mm')
    expect(statuses.join('\n')).toContain('3048 mm')
  })
  it('EXPORTS an in-bed full-sheet program: writes the EXACT verified text to the chosen path', async () => {
    const statuses: string[] = []
    const pickSavePath = vi.fn().mockResolvedValue('E:/usb/sheet_a.nc')
    const writeTextFile = vi.fn().mockResolvedValue(undefined)
    const outcome = await runLagunaExportSurface({
      gcodePath: 'C:/job/output/cam.nc',
      gateMachine: LAGUNA,
      suggestedPath: 'C:/job/output/job_laguna.nc',
      io: fakeIo(inBed),
      pickSavePath,
      writeTextFile,
      onStatus: (m) => statuses.push(m)
    })
    expect(outcome).toBe('exported')
    expect(pickSavePath).toHaveBeenCalledWith('C:/job/output/job_laguna.nc')
    expect(writeTextFile).toHaveBeenCalledTimes(1)
    expect(writeTextFile).toHaveBeenCalledWith('E:/usb/sheet_a.nc', inBed)
    expect(statuses.some((m) => m.includes('Exported for Laguna: E:/usb/sheet_a.nc'))).toBe(true)
  })
  it('CANCELLED dialog: nothing written, honest status', async () => {
    const statuses: string[] = []
    const writeTextFile = vi.fn().mockResolvedValue(undefined)
    const outcome = await runLagunaExportSurface({
      gcodePath: 'C:/job/output/cam.nc',
      gateMachine: LAGUNA,
      suggestedPath: 'C:/job/output/job_laguna.nc',
      io: fakeIo(inBed),
      pickSavePath: vi.fn().mockResolvedValue(null),
      writeTextFile,
      onStatus: (m) => statuses.push(m)
    })
    expect(outcome).toBe('cancelled')
    expect(writeTextFile).not.toHaveBeenCalled()
    expect(statuses.some((m) => m.includes('cancelled — no file written'))).toBe(true)
  })
  it('READ FAILURE is fail-closed: no dialog, no write', async () => {
    const pickSavePath = vi.fn()
    const writeTextFile = vi.fn()
    const outcome = await runLagunaExportSurface({
      gcodePath: 'C:/job/output/cam.nc',
      gateMachine: LAGUNA,
      suggestedPath: 'C:/job/output/job_laguna.nc',
      io: failingIo('EBUSY'),
      pickSavePath,
      writeTextFile,
      onStatus: () => undefined
    })
    expect(outcome).toBe('read_failed')
    expect(pickSavePath).not.toHaveBeenCalled()
    expect(writeTextFile).not.toHaveBeenCalled()
  })
})

// === (H) K2 Plus push surface -- ADVISORY-ONLY, can never block ==============

describe('runK2PushSurface -- the "Send to K2 Plus" action (advisories only)', () => {
  it('NEVER blocks: a G91-mixing, no-M5, 9-meter OrcaSlicer program still pushes', async () => {
    const statuses: string[] = []
    const moonrakerPush = vi.fn().mockResolvedValue({ ok: true, filename: 'part.gcode' })
    const outcome = await runK2PushSurface({
      gcodePath: 'C:/job/output/slice.gcode',
      machine: K2_PLUS,
      moonrakerUrl: 'http://k2.local',
      cfsSlotId: 2,
      io: fakeIo(ORCA_K2_GCODE),
      moonrakerPush,
      onStatus: (m) => statuses.push(m)
    })
    expect(outcome).toBe('sent')
    expect(moonrakerPush).toHaveBeenCalledTimes(1)
    const joined = statuses.join('\n')
    expect(joined).not.toContain('blocked')
    expect(joined).not.toContain('work area')
    expect(statuses.some((m) => m.includes('Started on K2 Plus: part.gcode'))).toBe(true)
  })
  it('threads machineId + cfsSlotId + startAfterUpload through the exact payload', async () => {
    const moonrakerPush = vi.fn().mockResolvedValue({ ok: true, filename: 'part.gcode' })
    await runK2PushSurface({
      gcodePath: 'C:/job/output/slice.gcode',
      machine: K2_PLUS,
      moonrakerUrl: 'http://k2.local',
      cfsSlotId: 2,
      io: fakeIo(ORCA_K2_GCODE),
      moonrakerPush,
      onStatus: () => undefined
    })
    expect(moonrakerPush).toHaveBeenCalledWith({
      gcodePath: 'C:/job/output/slice.gcode',
      printerUrl: 'http://k2.local',
      startAfterUpload: true,
      machineId: 'creality-k2-plus',
      cfsSlotId: 2
    })
  })
  it('emits AT MOST one compact advisory line, before the push result line', async () => {
    const statuses: string[] = []
    const moonrakerPush = vi.fn().mockResolvedValue({ ok: true, filename: 'part.gcode' })
    await runK2PushSurface({
      gcodePath: 'C:/job/output/slice.gcode',
      machine: K2_PLUS,
      moonrakerUrl: 'http://k2.local',
      cfsSlotId: 0,
      io: fakeIo(ORCA_K2_GCODE),
      moonrakerPush,
      onStatus: (m) => statuses.push(m)
    })
    const advisoryLines = statuses.filter((m) => m.startsWith('Pre-flight advisories (non-blocking):'))
    expect(advisoryLines.length).toBeLessThanOrEqual(1)
    expect(statuses[statuses.length - 1]).toContain('Started on K2 Plus')
  })
  it('a pre-flight read failure NEVER stops the push (main process re-reads the file)', async () => {
    const moonrakerPush = vi.fn().mockResolvedValue({ ok: true, filename: 'part.gcode' })
    const outcome = await runK2PushSurface({
      gcodePath: 'C:/job/output/slice.gcode',
      machine: K2_PLUS,
      moonrakerUrl: 'http://k2.local',
      cfsSlotId: 0,
      io: failingIo('EPERM'),
      moonrakerPush,
      onStatus: () => undefined
    })
    expect(outcome).toBe('sent')
    expect(moonrakerPush).toHaveBeenCalledTimes(1)
  })
  it('surfaces a temperature-validator rejection from the main process verbatim', async () => {
    // The temp validator lives in src/main/moonraker-push.ts (UNTOUCHED by
    // Wave 3m) -- this seam only relays its rejection text to the operator.
    const statuses: string[] = []
    const moonrakerPush = vi.fn().mockResolvedValue({
      ok: false,
      error: 'Upload blocked -- G-code exceeds machine temperature ceiling.',
      detail: 'M109 targets 400 C but the nozzle ceiling is 350 C.'
    })
    const outcome = await runK2PushSurface({
      gcodePath: 'C:/job/output/slice.gcode',
      machine: K2_PLUS,
      moonrakerUrl: 'http://k2.local',
      cfsSlotId: 0,
      io: fakeIo(ORCA_K2_GCODE),
      moonrakerPush,
      onStatus: (m) => statuses.push(m)
    })
    expect(outcome).toBe('send_failed')
    expect(
      statuses.some(
        (m) =>
          m.includes('Upload blocked -- G-code exceeds machine temperature ceiling.') &&
          m.includes('M109 targets 400 C')
      )
    ).toBe(true)
  })
  it('without a machine profile: no pre-flight, no machineId on the payload', async () => {
    const moonrakerPush = vi.fn().mockResolvedValue({ ok: true, filename: 'part.gcode' })
    const readTextFile = vi.fn().mockResolvedValue(ORCA_K2_GCODE)
    await runK2PushSurface({
      gcodePath: 'C:/job/output/slice.gcode',
      machine: undefined,
      moonrakerUrl: 'http://k2.local',
      cfsSlotId: 1,
      io: { readTextFile },
      moonrakerPush,
      onStatus: () => undefined
    })
    expect(readTextFile).not.toHaveBeenCalled()
    const payload = moonrakerPush.mock.calls[0]?.[0] as Record<string, unknown>
    expect(payload['machineId']).toBeUndefined()
  })
})

// === (I) setup-sheet notice -- non-blocking document surface =================

describe('formatSetupSheetGateNotice -- the setup-sheet (document) surface', () => {
  it('a FAILING program produces the honest saved-but-unshippable notice', () => {
    const gate = gateCncProgramForSend({
      gcode: lagunaProgram(['G1 X1600 Y100 Z-3 F2000']),
      machine: LAGUNA
    })
    const notice = formatSetupSheetGateNotice(gate)
    expect(notice).not.toBeNull()
    expect(notice).toContain('Setup sheet saved, but its embedded program FAILS the export safety gate')
    expect(notice).toContain('machine X work area')
  })
  it('a warnings-only program produces the advisory line', () => {
    // Missing the G0 Z25 safe retract => advisory, not a blocker.
    const gate = gateCncProgramForSend({
      gcode: ['G21', 'G90', 'G17', 'M3 S18000', 'G1 X10 Y10 Z-3 F600', 'M5', 'M30'].join('\n'),
      machine: LAGUNA
    })
    expect(gate.allowed).toBe(true)
    const notice = formatSetupSheetGateNotice(gate)
    expect(notice).not.toBeNull()
    expect(notice).toContain('Setup sheet program advisories (non-blocking):')
  })
  it('a clean program produces NO notice (null)', () => {
    const gate = gateCncProgramForSend({
      gcode: lagunaProgram(['G1 X100 Y100 Z-3 F2000']),
      machine: LAGUNA
    })
    expect(gate.allowed).toBe(true)
    expect(formatSetupSheetGateNotice(gate)).toBeNull()
  })
})

// === formatter contracts ======================================================

describe('operator-message formatters', () => {
  it('formatBlockedSendStatus counts the remaining errors honestly', () => {
    expect(formatBlockedSendStatus('Send to Carvera', ['first', 'second', 'third'])).toBe(
      'Send to Carvera blocked — posted G-code failed the export safety check: first (+2 more)'
    )
  })
  it('formatSendAdvisoriesStatus returns null for zero warnings (no status noise)', () => {
    expect(formatSendAdvisoriesStatus([])).toBeNull()
    expect(formatSendAdvisoriesStatus(['w1', 'w2'])).toBe(
      'Pre-flight advisories (non-blocking): w1 | w2'
    )
  })
})
