# SPDX-License-Identifier: MIT
#
# G-code snapshot/pattern tests for all 4 post-processor targets.
# These validate expected G-code output patterns without requiring FreeCAD runtime.

import re
import pytest
from integration.safety.validation_pipeline import validate_post_output, MACHINE_DIALECTS


# --- Expected G-code output fixtures ---

LAGUNA_GCODE = """\
%
; VCarve Pro post — Laguna Swift 5x10
G21
G90
G17
G94
G0 Z203.0
M3 S18000
G4 P2.0
M7
G0 X50.0 Y50.0
G1 Z-5.0 F1000
G1 X150.0 Y50.0 F2000
G1 X150.0 Y150.0
G1 X50.0 Y150.0
G1 X50.0 Y50.0
G0 Z25.0
M9
M5
G4 P3.0
G0 Z203.0
G0 X0 Y0
M30
%
"""

CARVERA_3AXIS_GCODE = """\
; Makera Carvera — 3-Axis G-code
G21
G90
G17
M6 T1
G43 H1
G0 Z140.0
M3 S12000
G4 P2
G0 X10.0 Y10.0
G1 Z-3.0 F500
G1 X50.0 F800
G1 Y50.0
G0 Z50.0
M5
G49
G0 Z140.0
G0 X0 Y0
M9
M2
"""

CARVERA_4AXIS_GCODE = """\
; Makera Carvera — 4-Axis Rotary G-code
G21
G90
G17
G0 Z46.0
G0 Y0
M3 S10000
G4 P2
G1 X10.0 Z-2.0 A0.0 F300
G1 X20.0 A45.0 F300
G1 X30.0 A90.0 F300
G1 X40.0 A135.0 F300
M5
G0 Z46.0
G0 A0
G0 X0 Y0
M9
M2
"""

K2_PLUS_GCODE = """\
; Generated by WorkTrackCAM for Creality K2 Plus
M104 S210
M140 S60
M109 S210
M190 S60
G28
G1 Z5 F3000
G1 X0.1 Y20 F5000
G1 X0.1 Y200 E15 F1500
M104 S0
M140 S0
M84
"""


class TestLagunaPostPattern:
    def test_has_tape_markers(self):
        lines = LAGUNA_GCODE.strip().splitlines()
        assert lines[0] == "%"
        assert lines[-1] == "%"

    def test_has_units_mode_plane(self):
        assert "G21" in LAGUNA_GCODE
        assert "G90" in LAGUNA_GCODE
        assert "G17" in LAGUNA_GCODE
        assert "G94" in LAGUNA_GCODE

    def test_spindle_warmup_dwell(self):
        assert "M3 S18000" in LAGUNA_GCODE
        assert "G4 P2.0" in LAGUNA_GCODE

    def test_dust_collection(self):
        lines = LAGUNA_GCODE.splitlines()
        m7_idx = next(i for i, l in enumerate(lines) if "M7" in l)
        m9_idx = next(i for i, l in enumerate(lines) if "M9" in l)
        assert m7_idx < m9_idx

    def test_spindle_cooldown_ramp(self):
        assert "M5" in LAGUNA_GCODE
        assert "G4 P3.0" in LAGUNA_GCODE

    def test_m30_end(self):
        assert "M30" in LAGUNA_GCODE

    def test_safe_z_retract(self):
        assert "G0 Z203.0" in LAGUNA_GCODE

    def test_passes_validation(self):
        result = validate_post_output(LAGUNA_GCODE, "Laguna_Swift_5x10")
        assert result.passed, f"Validation failed: {result.all_violations}"


class TestCarvera3AxisPostPattern:
    def test_has_units_mode_plane(self):
        assert "G21" in CARVERA_3AXIS_GCODE
        assert "G90" in CARVERA_3AXIS_GCODE
        assert "G17" in CARVERA_3AXIS_GCODE

    def test_atc_tool_change(self):
        assert "M6 T1" in CARVERA_3AXIS_GCODE
        assert "G43 H1" in CARVERA_3AXIS_GCODE

    def test_g49_cancel_tlc(self):
        assert "G49" in CARVERA_3AXIS_GCODE

    def test_m2_end(self):
        assert "M2" in CARVERA_3AXIS_GCODE
        assert "M30" not in CARVERA_3AXIS_GCODE

    def test_spindle_dwell(self):
        assert "G4 P2" in CARVERA_3AXIS_GCODE

    def test_passes_validation(self):
        result = validate_post_output(CARVERA_3AXIS_GCODE, "Makera_Carvera_3axis")
        assert result.passed, f"Validation failed: {result.all_violations}"


class TestCarvera4AxisPostPattern:
    def test_y0_centering(self):
        assert "G0 Y0" in CARVERA_4AXIS_GCODE

    def test_a_axis_output(self):
        a_lines = [l for l in CARVERA_4AXIS_GCODE.splitlines() if re.search(r"\bA\d", l)]
        assert len(a_lines) >= 2

    def test_a0_return(self):
        assert "G0 A0" in CARVERA_4AXIS_GCODE

    def test_no_atc(self):
        assert "M6" not in CARVERA_4AXIS_GCODE
        assert "G43" not in CARVERA_4AXIS_GCODE

    def test_m2_end(self):
        assert "M2" in CARVERA_4AXIS_GCODE
        assert "M30" not in CARVERA_4AXIS_GCODE

    def test_passes_validation(self):
        result = validate_post_output(CARVERA_4AXIS_GCODE, "Makera_Carvera_4axis")
        assert result.passed, f"Validation failed: {result.all_violations}"


class TestK2PlusFDMPattern:
    def test_nozzle_temp(self):
        assert "M104 S210" in K2_PLUS_GCODE

    def test_bed_temp(self):
        assert "M140 S60" in K2_PLUS_GCODE

    def test_temps_within_ceiling(self):
        result = validate_post_output(K2_PLUS_GCODE, "Creality_K2_Plus")
        assert len(result.temp_violations) == 0

    def test_over_ceiling_detected(self):
        bad_gcode = K2_PLUS_GCODE.replace("M104 S210", "M104 S400")
        result = validate_post_output(bad_gcode, "Creality_K2_Plus")
        assert not result.passed
        assert len(result.temp_violations) == 1


class TestValidationPipeline:
    def test_unknown_machine_fails(self):
        result = validate_post_output("G0 X0", "NonExistent_Machine")
        assert not result.passed

    def test_all_machines_have_dialects(self):
        expected = ["Laguna_Swift_5x10", "Makera_Carvera_3axis", "Makera_Carvera_4axis", "Creality_K2_Plus"]
        for machine_id in expected:
            assert machine_id in MACHINE_DIALECTS

    def test_laguna_dialect_is_mach3(self):
        assert MACHINE_DIALECTS["Laguna_Swift_5x10"].dialect == "mach3"

    def test_carvera_dialect_is_grbl(self):
        assert MACHINE_DIALECTS["Makera_Carvera_3axis"].dialect == "grbl"
        assert MACHINE_DIALECTS["Makera_Carvera_4axis"].dialect == "grbl"
