# SPDX-License-Identifier: MIT
#
# End-to-end integration tests for the WorkTrackCAM FreeCAD addon.
# These verify that the complete pipeline works for each machine:
# G-code generation -> safety validation -> machine-specific checks.

import json
import pathlib
import pytest

from integration.safety.validation_pipeline import validate_post_output, MACHINE_DIALECTS
from integration.laguna.vacuum_allocator import allocate_zones, engaged_zone_indices, SHEET_PRESETS
from integration.laguna.vacuum_postlude import wrap_gcode_with_vacuum
from integration.carvera.atc_sequencer import AtcCapability, sequence_multi_tool_job
from integration.carvera.rotary_ops import (
    RotaryJobSetup,
    RotaryStrategy,
    plan_operation,
    operation_to_gcode,
)
from integration.carvera.rotary_collision import RotaryFixture, sweep_segments
from integration.moonraker.client import MoonrakerConfig
from integration.moonraker.temp_validator import TempCeilings, validate_gcode_temps
from integration.slicer.cura_engine import PRESETS
from integration.slicer.k2_presets import get_k2_settings, get_k2_start_gcode, get_k2_end_gcode


ADDON_ROOT = pathlib.Path(__file__).resolve().parent.parent


# --- Laguna Swift 5x10 end-to-end ---

class TestLagunaEndToEnd:
    LAGUNA_GCODE = """\
%
; VCarve Pro post — Laguna Swift 5x10
G21
G90
G17
G94
G0 Z203.0
M3 S18000
G4 P2.0
M7
G0 X50.0 Y50.0
G1 Z-5.0 F1000
G1 X150.0 Y50.0 F2000
G1 X150.0 Y150.0
G0 Z25.0
M9
M5
G4 P3.0
G0 Z203.0
G0 X0 Y0
M30
%
"""

    def test_full_sheet_workflow(self):
        allocations = allocate_zones(0, 0, *SHEET_PRESETS["full_4x8"])
        engaged = engaged_zone_indices(allocations)
        assert len(engaged) > 0

        wrapped = wrap_gcode_with_vacuum(self.LAGUNA_GCODE, engaged)
        assert "M64" in wrapped
        assert "M65" in wrapped

        result = validate_post_output(self.LAGUNA_GCODE, "Laguna_Swift_5x10")
        assert result.passed

    def test_half_sheet_engages_fewer_zones(self):
        full_alloc = allocate_zones(0, 0, *SHEET_PRESETS["full_4x8"])
        half_alloc = allocate_zones(0, 0, *SHEET_PRESETS["half_4x4"])
        full_engaged = engaged_zone_indices(full_alloc)
        half_engaged = engaged_zone_indices(half_alloc)
        assert len(half_engaged) <= len(full_engaged)


# --- Makera Carvera 3-axis end-to-end ---

class TestCarvera3AxisEndToEnd:
    CARVERA_GCODE = """\
; Makera Carvera — 3-Axis G-code
G21
G90
G17
M6 T1
G43 H1
G0 Z140.0
M3 S12000
G4 P2
G0 X10.0 Y10.0
G1 Z-3.0 F500
G1 X50.0 F800
G0 Z50.0
M5
G49
G0 Z140.0
G0 X0 Y0
M9
M2
"""

    def test_validation_passes(self):
        result = validate_post_output(self.CARVERA_GCODE, "Makera_Carvera_3axis")
        assert result.passed

    def test_multi_tool_atc_sequence(self):
        atc = AtcCapability(slot_count=6)
        blocks = sequence_multi_tool_job([1, 2, 3, 2], atc)
        assert len(blocks) == 4
        assert blocks[0].tool_number == 1
        assert blocks[1].tool_number == 2
        assert blocks[2].tool_number == 3
        assert blocks[3].tool_number == 2


# --- Makera Carvera 4-axis end-to-end ---

class TestCarvera4AxisEndToEnd:
    def test_rotary_plan_and_validate(self):
        setup = RotaryJobSetup(
            stock_diameter_mm=50,
            stock_length_mm=100,
            strategy=RotaryStrategy.ROUGHING,
            a_step_deg=45,
            stepdown_mm=1.0,
            spindle_rpm=10000,
        )
        op = plan_operation(setup, depth_mm=3.0)
        gcode = operation_to_gcode(op)
        assert "G21" in gcode
        assert "M2" in gcode
        assert "G0 Y0" in gcode
        assert "G0 A0" in gcode

    def test_rotary_collision_check_safe(self):
        fixture = RotaryFixture(chuck_outer_radius_mm=46)
        segments = [
            (50, 0, 30),
            (100, 0, 30),
            (150, 0, 30),
        ]
        result = sweep_segments(segments, tool_radius=3.175, fixture=fixture)
        assert not result.has_collision

    def test_rotary_collision_check_collision(self):
        fixture = RotaryFixture(chuck_outer_radius_mm=46)
        segments = [
            (5, 0, 40),
            (5, 0, 50),
        ]
        result = sweep_segments(segments, tool_radius=3.175, fixture=fixture)
        assert result.has_collision

    def test_all_strategies_produce_gcode(self):
        for strategy in RotaryStrategy:
            setup = RotaryJobSetup(
                stock_diameter_mm=50,
                stock_length_mm=100,
                strategy=strategy,
            )
            op = plan_operation(setup, 2.0)
            gcode = operation_to_gcode(op)
            assert len(gcode) > 0
            assert "G21" in gcode


# --- K2 Plus end-to-end ---

class TestK2PlusEndToEnd:
    K2_GCODE = """\
; Generated by WorkTrackCAM for Creality K2 Plus
M104 S210
M140 S60
M109 S210
M190 S60
G28
G1 Z5 F3000
G1 X0.1 Y20 F5000
G1 X0.1 Y200 E15 F1500
M104 S0
M140 S0
M84
"""

    def test_validation_passes(self):
        result = validate_post_output(self.K2_GCODE, "Creality_K2_Plus")
        assert result.passed

    def test_temp_validation_catches_overtemp(self):
        bad_gcode = self.K2_GCODE.replace("M104 S210", "M104 S400")
        violations = validate_gcode_temps(bad_gcode, TempCeilings(max_nozzle_c=350))
        assert len(violations) == 1
        assert violations[0].component == "nozzle"

    def test_k2_presets_are_within_ceilings(self):
        ceilings = TempCeilings(max_nozzle_c=350, max_bed_c=120)
        for name, preset in PRESETS.items():
            assert preset.nozzle_temp_c <= ceilings.max_nozzle_c, f"{name} nozzle too hot"
            assert preset.bed_temp_c <= ceilings.max_bed_c, f"{name} bed too hot"

    def test_k2_start_gcode_validates(self):
        gcode = get_k2_start_gcode("standard") + "\n" + get_k2_end_gcode()
        violations = validate_gcode_temps(gcode, TempCeilings())
        assert len(violations) == 0


# --- Machine profile integrity ---

class TestMachineProfileIntegrity:
    def test_all_fcm_files_are_valid_json(self):
        machines_dir = ADDON_ROOT / "machines"
        for fcm_file in machines_dir.glob("*.fcm"):
            with open(fcm_file) as f:
                data = json.load(f)
            assert "name" in data, f"{fcm_file.name} missing name"
            has_axes = "axes" in data or "linear_axes" in data
            assert has_axes, f"{fcm_file.name} missing axes or linear_axes"

    def test_all_machines_have_validation_dialects(self):
        machines_dir = ADDON_ROOT / "machines"
        for fcm_file in machines_dir.glob("*.fcm"):
            machine_id = fcm_file.stem
            assert machine_id in MACHINE_DIALECTS, f"{machine_id} missing from MACHINE_DIALECTS"

    def test_post_processor_files_exist(self):
        posts_dir = ADDON_ROOT / "posts"
        expected = [
            "richauto_a_series.py",
            "makera_carvera.py",
            "makera_carvera_4axis.py",
            "klipper_moonraker.py",
        ]
        for name in expected:
            assert (posts_dir / name).exists(), f"Missing post-processor: {name}"

    def test_addon_package_xml_exists(self):
        assert (ADDON_ROOT / "package.xml").exists()

    def test_init_files_exist(self):
        assert (ADDON_ROOT / "Init.py").exists()
        assert (ADDON_ROOT / "InitGui.py").exists()
