/**
 * Focused branch coverage for `src/main/moonrakerPush`'s advisory
 * warning-assembly logic (the `warnings[]` + `headerHealth` block at
 * lines ~449-492 of `moonraker-push.ts`).
 *
 * Why a new file
 * --------------
 * The existing Moonraker suites already lock down:
 *   - `parseMoonrakerStatusBody` / `parseUploadedPath` / `buildUploadUrlForK2Cfs`
 *     pure parsers (`moonraker-push.test.ts` + `moonraker-push-pin.test.ts`).
 *   - wire-level push / status / cancel / pause / resume + the [ID-0073]
 *     temp-ceiling gate + the [ID-0075] bounded-read cap
 *     (`moonraker-push-e2e.test.ts`).
 *   - the thumbnail-present vs thumbnail-missing warning poles
 *     (`moonraker-push-thumbnail.test.ts`).
 *
 * What was still UNCOVERED (this file) -- all reachable purely by varying
 * the fixture header content and mocking the same network boundary the
 * other suites use (`./__mocks__/moonraker-fake`):
 *   (A) The Klipper power-loss-recovery advisory branch (push warns when
 *       the start gcode carries no `SAVE_VARIABLE VARIABLE=was_interrupted`
 *       sentinel) -- moonraker-push.ts line ~477.
 *   (B) The adaptive-probing advisory branch (push warns when no
 *       `; MINX = ... ; MAXX = ...` / `BED_MESH_CALIBRATE` sentinel) --
 *       line ~484.
 *   (C) The non-thumbnail missing-fields advisory branch (push warns
 *       "missing time, filament, ..." when SOME-but-not-all of the four
 *       advisory fields are absent) -- lines ~458-468.
 *   (D) The "no-nag on a non-slicer file" suppression: when ALL FOUR
 *       advisory fields are missing (`missingFields.length === 4`, i.e. a
 *       raw CNC G-code), the push must NOT emit the non-thumbnail-field
 *       warning NOR the PLR / probing warnings -- only the always-on
 *       thumbnail warning fires. lines ~458 + ~476 guard.
 *   (E) Warnings + headerHealth survive onto the `startAfterUpload: true`
 *       success result (lines ~567-575), not just the upload-only result.
 *   (F) A fully-clean K2 Plus header (all four fields + PLR + probing)
 *       produces ZERO warnings even on the start-print path.
 *
 * Safety: advisory warnings are NEVER blockers -- every assertion below
 * also confirms `ok === true` and that the file still reached the wire
 * (`state.captured.length >= 1`). Safety Rule 1 (G-code is sacred) holds:
 * this module only reads the header; it never mutates the bytes.
 *
 * Three-machine scope: the Creality K2 Plus is the ONLY Moonraker target.
 * The Laguna Swift 5x10 (RichAuto) and Makera Carvera (4-axis) CNC routes
 * do not use Moonraker and are out-of-scope here.
 */
import { mkdtempSync, writeFileSync } from 'node:fs'
import { type Server } from 'node:http'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { moonrakerPush } from './moonraker-push'
import {
  freshMockMoonrakerState,
  resetMockMoonrakerState,
  startMockMoonraker,
  stopMockMoonraker,
  type MockMoonrakerState,
} from './__mocks__/moonraker-fake'

// ─── Fixtures (pure-ASCII so the multipart body stays byte-stable) ───────────

// A: thumbnail + all four advisory fields + adaptive probing present, but
// NO power-loss-recovery sentinel. Isolates the PLR advisory branch: the
// only warning that should fire is the missing-PLR one.
const G_NO_PLR = [
  '; generated by OrcaSlicer 2.1.1',
  '; estimated printing time (normal mode) = 1h 0m 0s',
  '; filament used [mm] = 1000.0',
  '; total layer number: 50',
  '; thumbnail begin 300x300 8400',
  '; iVBORw0KGgoAAAANSUhEUgAA...',
  '; thumbnail end',
  '; MINX = 10.0',
  '; MAXX = 200.0',
  'M140 S60',
  'M104 S210',
  'G28',
  '',
].join('\n')

// B: thumbnail + all four advisory fields + PLR present, but NO
// adaptive-probing sentinel. Isolates the adaptive-probing advisory branch.
const G_NO_PROBING = [
  '; generated by OrcaSlicer 2.1.1',
  '; estimated printing time (normal mode) = 1h 0m 0s',
  '; filament used [mm] = 1000.0',
  '; total layer number: 50',
  '; thumbnail begin 300x300 8400',
  '; iVBORw0KGgoAAAANSUhEUgAA...',
  '; thumbnail end',
  'SAVE_VARIABLE VARIABLE=was_interrupted VALUE=True',
  'M140 S60',
  'M104 S210',
  'G28',
  '',
].join('\n')

// C: thumbnail PRESENT (so the thumbnail warning does NOT fire) + PLR +
// probing present, but SOME advisory fields missing (no filament, no layer
// count -> 2 of 4 missing). Isolates the non-thumbnail missing-fields
// advisory branch (missingFields.length is 2, i.e. > 0 and < 4).
const G_PARTIAL_FIELDS = [
  '; generated by OrcaSlicer 2.1.1',
  '; estimated printing time (normal mode) = 1h 0m 0s',
  '; thumbnail begin 300x300 8400',
  '; iVBORw0KGgoAAAANSUhEUgAA...',
  '; thumbnail end',
  '; MINX = 10.0',
  '; MAXX = 200.0',
  'SAVE_VARIABLE VARIABLE=was_interrupted VALUE=True',
  'M140 S60',
  'M104 S210',
  'G28',
  '',
].join('\n')

// D: a raw CNC-style G-code with NONE of the four slicer advisory fields,
// no thumbnail, no PLR, no probing. missingFields.length === 4, which the
// push uses as the "this is not a slicer file -- do not nag" sentinel.
const G_RAW_CNC = [
  '; plain toolpath, no slicer header',
  'G21',
  'G90',
  'G0 X0 Y0 Z5',
  'G1 Z-1 F300',
  'G1 X10 Y10 F1200',
  'M5',
  '',
].join('\n')

// F: the fully-clean K2 Plus header -- all four advisory fields + thumbnail
// + PLR + adaptive probing. Must produce ZERO advisory warnings even on the
// start-print path (mirrors the bundled WorkTrackCAM OrcaSlicer K2 profile).
const G_CLEAN_K2 = [
  '; generated by OrcaSlicer 2.1.1',
  '; estimated printing time (normal mode) = 1h 23m 45s',
  '; filament used [mm] = 1234.56',
  '; filament used [g] = 12.34',
  '; total layer number: 88',
  '; thumbnail begin 300x300 8400',
  '; iVBORw0KGgoAAAANSUhEUgAA...',
  '; thumbnail end',
  ';SET PRINT AREA MIN AND MAX COORDINATES TO ENABLE ADAPTIVE PROBING',
  '; MINX = 10.0',
  '; MAXX = 200.0',
  'SAVE_VARIABLE VARIABLE=was_interrupted VALUE=True',
  'M140 S60',
  'M104 S210',
  'G28',
  '',
].join('\n')

const fixtureDir = mkdtempSync(join(tmpdir(), 'moonraker-coverage-'))
const fNoPlr = join(fixtureDir, 'no-plr.gcode')
const fNoProbing = join(fixtureDir, 'no-probing.gcode')
const fPartialFields = join(fixtureDir, 'partial-fields.gcode')
const fRawCnc = join(fixtureDir, 'raw-cnc.gcode')
const fCleanK2 = join(fixtureDir, 'clean-k2.gcode')
writeFileSync(fNoPlr, G_NO_PLR)
writeFileSync(fNoProbing, G_NO_PROBING)
writeFileSync(fPartialFields, G_PARTIAL_FIELDS)
writeFileSync(fRawCnc, G_RAW_CNC)
writeFileSync(fCleanK2, G_CLEAN_K2)

describe('moonrakerPush advisory-warning branch coverage', () => {
  let server: Server
  let baseUrl: string
  let state: MockMoonrakerState

  beforeAll(async () => {
    state = freshMockMoonrakerState()
    const booted = await startMockMoonraker(state)
    server = booted.server
    baseUrl = booted.url
  })

  afterAll(async () => {
    await stopMockMoonraker(server)
  })

  beforeEach(() => {
    resetMockMoonrakerState(state)
  })

  // ─── A. Power-loss-recovery advisory branch ──────────────────────────────
  describe('power-loss-recovery advisory (line ~477)', () => {
    it('warns about missing Klipper PLR sentinel but still uploads (ok=true)', async () => {
      const r = await moonrakerPush({ gcodePath: fNoPlr, printerUrl: baseUrl, timeoutMs: 5_000 })
      expect(r.ok).toBe(true)
      expect(state.captured.length).toBe(1)
      if (r.ok) {
        const joined = (r.warnings ?? []).join('\n')
        expect(joined).toMatch(/power-loss recovery/i)
        expect(joined).toMatch(/was_interrupted/)
        // headerHealth records the structural flag for the renderer badge.
        expect(r.headerHealth?.fields.hasPowerLossRecovery).toBeUndefined()
        // Probing IS present in this fixture -> no probing warning.
        expect(joined).not.toMatch(/adaptive-probing sentinel/i)
        // Thumbnail + all four advisory fields present -> no thumbnail /
        // missing-fields warnings either.
        expect(joined).not.toMatch(/thumbnail begin/i)
        expect(r.headerHealth?.ok).toBe(true)
      }
    })
  })

  // ─── B. Adaptive-probing advisory branch ─────────────────────────────────
  describe('adaptive-probing advisory (line ~484)', () => {
    it('warns about missing adaptive-probing sentinel but still uploads (ok=true)', async () => {
      const r = await moonrakerPush({ gcodePath: fNoProbing, printerUrl: baseUrl, timeoutMs: 5_000 })
      expect(r.ok).toBe(true)
      expect(state.captured.length).toBe(1)
      if (r.ok) {
        const joined = (r.warnings ?? []).join('\n')
        expect(joined).toMatch(/adaptive-probing sentinel/i)
        expect(joined).toMatch(/BED_MESH_CALIBRATE/)
        // PLR IS present in this fixture -> no PLR warning.
        expect(joined).not.toMatch(/power-loss recovery/i)
        expect(r.headerHealth?.fields.hasAdaptiveProbing).toBeUndefined()
        expect(r.headerHealth?.fields.hasPowerLossRecovery).toBe(true)
      }
    })
  })

  // ─── C. Non-thumbnail missing-fields advisory branch ─────────────────────
  describe('non-thumbnail missing-fields advisory (lines ~458-468)', () => {
    it('warns listing only the non-thumbnail missing fields when SOME are absent', async () => {
      const r = await moonrakerPush({
        gcodePath: fPartialFields,
        printerUrl: baseUrl,
        timeoutMs: 5_000,
      })
      expect(r.ok).toBe(true)
      expect(state.captured.length).toBe(1)
      if (r.ok) {
        const joined = (r.warnings ?? []).join('\n')
        // filament + layerCount missing -> both named in the advisory.
        expect(joined).toMatch(/missing .*filament/i)
        expect(joined).toMatch(/layerCount/)
        // 'thumbnail' must NOT appear in the missing-fields list (the
        // thumbnail block is present, so it is filtered out by the
        // nonThumbnail filter even though it shares the field enum).
        const missingFieldsLine = (r.warnings ?? []).find((w) => /slicer header is missing/i.test(w))
        expect(missingFieldsLine).toBeDefined()
        expect(missingFieldsLine).not.toMatch(/thumbnail/)
        // Structural: headerHealth reports exactly the two missing fields.
        expect(r.headerHealth?.missingFields).toEqual(
          expect.arrayContaining(['filament', 'layerCount']),
        )
        expect(r.headerHealth?.missingFields).not.toContain('thumbnail')
        expect(r.headerHealth?.missingFields).not.toContain('time')
      }
    })
  })

  // ─── D. No-nag suppression on a raw (non-slicer) G-code ───────────────────
  describe('no-nag suppression when all four advisory fields are missing', () => {
    it('emits ONLY the thumbnail warning for a raw CNC file -- no field/PLR/probing nags', async () => {
      const r = await moonrakerPush({ gcodePath: fRawCnc, printerUrl: baseUrl, timeoutMs: 5_000 })
      expect(r.ok).toBe(true)
      expect(state.captured.length).toBe(1)
      if (r.ok) {
        const warnings = r.warnings ?? []
        const joined = warnings.join('\n')
        // The always-on thumbnail warning DOES fire (thumbnail is absent).
        expect(joined).toMatch(/thumbnail/i)
        // But the missing-fields / PLR / probing advisories must be
        // suppressed because missingFields.length === 4 (not a slicer file).
        expect(joined).not.toMatch(/slicer header is missing/i)
        expect(joined).not.toMatch(/power-loss recovery/i)
        expect(joined).not.toMatch(/adaptive-probing sentinel/i)
        // Exactly one advisory warning total (the thumbnail one).
        expect(warnings.length).toBe(1)
        expect(r.headerHealth?.missingFields).toHaveLength(4)
        expect(r.headerHealth?.ok).toBe(false)
      }
    })
  })

  // ─── E. Warnings survive onto the start-print success result ──────────────
  describe('warnings + headerHealth thread onto the startAfterUpload result (lines ~567-575)', () => {
    it('carries advisory warnings AND headerHealth when the print is also started', async () => {
      const r = await moonrakerPush({
        gcodePath: fNoPlr,
        printerUrl: baseUrl,
        startAfterUpload: true,
        timeoutMs: 5_000,
      })
      expect(r.ok).toBe(true)
      // upload + start -> two captured requests.
      expect(state.captured.length).toBe(2)
      expect(state.captured[1]?.path.startsWith('/printer/print/start')).toBe(true)
      if (r.ok) {
        expect(r.printStarted).toBe(true)
        expect((r.warnings ?? []).join('\n')).toMatch(/power-loss recovery/i)
        // headerHealth must also survive onto the print-started branch.
        expect(r.headerHealth).toBeDefined()
        expect(r.headerHealth?.ok).toBe(true)
      }
    })
  })

  // ─── F. Clean K2 header -> zero warnings even on the start path ────────────
  describe('fully-clean K2 Plus header produces zero advisory warnings', () => {
    it('omits the warnings key entirely when the header is complete (upload + start)', async () => {
      const r = await moonrakerPush({
        gcodePath: fCleanK2,
        printerUrl: baseUrl,
        startAfterUpload: true,
        timeoutMs: 5_000,
      })
      expect(r.ok).toBe(true)
      if (r.ok) {
        expect(r.printStarted).toBe(true)
        // The push spreads `warnings` onto the result only when non-empty,
        // so a clean header means the key is absent (not an empty array).
        expect(r.warnings).toBeUndefined()
        expect(r.headerHealth?.ok).toBe(true)
        expect(r.headerHealth?.fields.hasPowerLossRecovery).toBe(true)
        expect(r.headerHealth?.fields.hasAdaptiveProbing).toBe(true)
        expect(r.headerHealth?.missingFields).toEqual([])
      }
    })
  })
})
