/**
 * Integration tests for the K2 Plus thumbnail-block verification path in
 * `moonrakerPush`. The push function now feeds the bounded header text to
 * `checkGcodeHeaderHealth` / `hasThumbnailBlock` and surfaces a non-fatal
 * warning on the result when the slicer-emitted thumbnail PNG is missing
 * (Mainsail/Fluidd would otherwise show a plain filename in the K2 file
 * picker).
 *
 * Boots the shared mock Moonraker harness (`__mocks__/moonraker-fake.ts`)
 * so we can assert end-to-end that:
 *   - A G-code WITH a `; thumbnail begin` block uploads cleanly and the
 *     result carries NO thumbnail warning.
 *   - A G-code WITHOUT a thumbnail block still uploads (Safety: warnings
 *     are advisory), the result is ok=true, and `warnings[]` mentions
 *     the missing thumbnail.
 *
 * Quick-win bundle (undo/redo + K2 thumbnail + Klipper header).
 */
import { mkdtempSync, writeFileSync } from 'node:fs'
import { type Server } from 'node:http'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { moonrakerPush } from './moonraker-push'
import {
  freshMockMoonrakerState,
  resetMockMoonrakerState,
  startMockMoonraker,
  stopMockMoonraker,
  type MockMoonrakerState,
} from './__mocks__/moonraker-fake'

// Pure-ASCII fixtures so the multipart body is byte-stable.
//
// G_WITH_THUMBNAIL mirrors what the bundled K2 Plus OrcaSlicer profile
// emits today: all four legacy advisory fields (time / filament /
// layerCount / thumbnail) AND the K2-specific MINX/MAXX adaptive-probing
// annotation AND the Klipper PLR sentinel that the K2 START_PRINT macro
// expects. This is the "clean" fixture -- the moonraker push must report
// zero advisory warnings on it.
const G_WITH_THUMBNAIL = [
  '; generated by OrcaSlicer 2.1.1 on 2026-05-27',
  '; estimated printing time (normal mode) = 1h 23m 45s',
  '; filament used [mm] = 1234.56',
  '; filament used [g] = 12.34',
  '; total layer number: 88',
  '; thumbnail begin 300x300 8400',
  '; iVBORw0KGgoAAAANSUhEUgAAASwAAA...',
  '; ...moreBase64...',
  '; thumbnail end',
  ';SET PRINT AREA MIN AND MAX COORDINATES TO ENABLE ADAPTIVE PROBING',
  '; MINX = 10.0',
  '; MINY = 10.0',
  '; MAXX = 200.0',
  '; MAXY = 200.0',
  'SAVE_VARIABLE VARIABLE=was_interrupted VALUE=True',
  'M140 S60',
  'M104 S210',
  'G28',
  '',
].join('\n')

const G_WITHOUT_THUMBNAIL = [
  '; generated by SomeSlicer (thumbnails disabled)',
  '; estimated printing time (normal mode) = 30m',
  '; filament used [mm] = 500',
  '; total layer number: 40',
  'M140 S60',
  'M104 S210',
  'G28',
  '',
].join('\n')

const fixtureDir = mkdtempSync(join(tmpdir(), 'moonraker-thumbnail-'))
const fixtureWith = join(fixtureDir, 'with-thumb.gcode')
const fixtureWithout = join(fixtureDir, 'without-thumb.gcode')
writeFileSync(fixtureWith, G_WITH_THUMBNAIL)
writeFileSync(fixtureWithout, G_WITHOUT_THUMBNAIL)

describe('moonrakerPush K2 thumbnail verification (quick-win bundle)', () => {
  let server: Server
  let baseUrl: string
  let state: MockMoonrakerState

  beforeAll(async () => {
    state = freshMockMoonrakerState()
    const booted = await startMockMoonraker(state)
    server = booted.server
    baseUrl = booted.url
  })

  afterAll(async () => {
    await stopMockMoonraker(server)
  })

  beforeEach(() => {
    resetMockMoonrakerState(state)
  })

  it('uploads cleanly with no thumbnail warning when the block is present', async () => {
    const r = await moonrakerPush({
      gcodePath: fixtureWith,
      printerUrl: baseUrl,
      timeoutMs: 5_000,
    })
    expect(r.ok).toBe(true)
    if (r.ok) {
      expect(r.warnings ?? []).toEqual([])
      expect(r.headerHealth?.fields.thumbnail?.widthPx).toBe(300)
      expect(r.headerHealth?.fields.thumbnail?.heightPx).toBe(300)
      expect(r.headerHealth?.fields.thumbnail?.bytes).toBe(8400)
      expect(r.headerHealth?.ok).toBe(true)
    }
  })

  it('surfaces a non-fatal warning when the thumbnail block is missing', async () => {
    const r = await moonrakerPush({
      gcodePath: fixtureWithout,
      printerUrl: baseUrl,
      timeoutMs: 5_000,
    })
    expect(r.ok).toBe(true)
    if (r.ok) {
      expect(r.warnings).toBeDefined()
      expect(r.warnings!.length).toBeGreaterThanOrEqual(1)
      // The warning must mention the missing thumbnail so the user can
      // act on it (re-slice with thumbnails enabled).
      expect(r.warnings!.join('\n')).toMatch(/thumbnail/i)
      // Header health must report the missing field structurally so the
      // renderer can render a focused badge.
      expect(r.headerHealth?.ok).toBe(false)
      expect(r.headerHealth?.missingFields).toContain('thumbnail')
    }
  })

  it('upload still succeeds (warnings are advisory, never blocking)', async () => {
    const r = await moonrakerPush({
      gcodePath: fixtureWithout,
      printerUrl: baseUrl,
      timeoutMs: 5_000,
    })
    expect(r.ok).toBe(true)
  })
})
